import os

names = {
    ".ENV": "dotenv.svg",
    ".NET": "dotnet.svg",
    "/e/": "e.svg",
    "1001Tracklists": "1001tracklists.svg",
    "1Password": "1password.svg",
    "3M": "3m.svg",
    "42": "42.svg",
    "4chan": "4chan.svg",
    "4D": "4d.svg",
    "500px": "500px.svg",
    "A-Frame": "aframe.svg",
    "ABB RobotStudio": "abbrobotstudio.svg",
    "Abbott": "abbott.svg",
    "Abbvie": "abbvie.svg",
    "Ableton Live": "abletonlive.svg",
    "About.me": "aboutdotme.svg",
    "Abstract": "abstract.svg",
    "Academia": "academia.svg",
    "Accenture": "accenture.svg",
    "Acclaim": "acclaim.svg",
    "Accusoft": "accusoft.svg",
    "Acer": "acer.svg",
    "ACM": "acm.svg",
    "ActiGraph": "actigraph.svg",
    "Activision": "activision.svg",
    "Adafruit": "adafruit.svg",
    "AdBlock": "adblock.svg",
    "Adblock Plus": "adblockplus.svg",
    "AddThis": "addthis.svg",
    "AdGuard": "adguard.svg",
    "Adidas": "adidas.svg",
    "Adminer": "adminer.svg",
    "Adobe": "adobe.svg",
    "Adobe Acrobat Reader": "adobeacrobatreader.svg",
    "Adobe After Effects": "adobeaftereffects.svg",
    "Adobe Audition": "adobeaudition.svg",
    "Adobe Creative Cloud": "adobecreativecloud.svg",
    "Adobe Dreamweaver": "adobedreamweaver.svg",
    "Adobe Fonts": "adobefonts.svg",
    "Adobe Illustrator": "adobeillustrator.svg",
    "Adobe InDesign": "adobeindesign.svg",
    "Adobe Lightroom": "adobelightroom.svg",
    "Adobe Lightroom Classic": "adobelightroomclassic.svg",
    "Adobe Photoshop": "adobephotoshop.svg",
    "Adobe Premiere Pro": "adobepremierepro.svg",
    "Adobe XD": "adobexd.svg",
    "AdonisJS": "adonisjs.svg",
    "ADP": "adp.svg",
    "Adyen": "adyen.svg",
    "Aer Lingus": "aerlingus.svg",
    "Aeroflot": "aeroflot.svg",
    "Aeroméxico": "aeromexico.svg",
    "Aerospike": "aerospike.svg",
    "AEW": "aew.svg",
    "Affinity": "affinity.svg",
    "Affinity Designer": "affinitydesigner.svg",
    "Affinity Photo": "affinityphoto.svg",
    "Affinity Publisher": "affinitypublisher.svg",
    "Agora": "agora.svg",
    "AI Dungeon": "aidungeon.svg",
    "AIB": "aib.svg",
    "AIOHTTP": "aiohttp.svg",
    "Aiqfome": "aiqfome.svg",
    "Air Canada": "aircanada.svg",
    "Air China": "airchina.svg",
    "Air France": "airfrance.svg",
    "AirAsia": "airasia.svg",
    "Airbnb": "airbnb.svg",
    "Airbus": "airbus.svg",
    "Airbyte": "airbyte.svg",
    "Aircall": "aircall.svg",
    "AirPlay Audio": "airplayaudio.svg",
    "AirPlay Video": "airplayvideo.svg",
    "Airtable": "airtable.svg",
    "Ajv": "ajv.svg",
    "Alacritty": "alacritty.svg",
    "Albert Heijn": "albertheijn.svg",
    "Aldi Nord": "aldinord.svg",
    "Aldi Süd": "aldisud.svg",
    "Alfa Romeo": "alfaromeo.svg",
    "Alfred": "alfred.svg",
    "Algolia": "algolia.svg",
    "Algorand": "algorand.svg",
    "Alibaba Cloud": "alibabacloud.svg",
    "Alibaba.com": "alibabadotcom.svg",
    "AliExpress": "aliexpress.svg",
    "Alipay": "alipay.svg",
    "Alitalia": "alitalia.svg",
    "Allegro": "allegro.svg",
    "AlliedModders": "alliedmodders.svg",
    "AlloCiné": "allocine.svg",
    "AllTrails": "alltrails.svg",
    "Alpine Linux": "alpinelinux.svg",
    "Alpine.js": "alpinedotjs.svg",
    "Altium Designer": "altiumdesigner.svg",
    "Alwaysdata": "alwaysdata.svg",
    "Amazon": "amazon.svg",
    "Amazon Alexa": "amazonalexa.svg",
    "Amazon API Gateway": "amazonapigateway.svg",
    "Amazon AWS": "amazonaws.svg",
    "Amazon CloudWatch": "amazoncloudwatch.svg",
    "Amazon DynamoDB": "amazondynamodb.svg",
    "Amazon EC2": "amazonec2.svg",
    "Amazon ECS": "amazonecs.svg",
    "Amazon EKS": "amazoneks.svg",
    "Amazon Fire TV": "amazonfiretv.svg",
    "Amazon Games": "amazongames.svg",
    "Amazon Lumberyard": "amazonlumberyard.svg",
    "Amazon Pay": "amazonpay.svg",
    "Amazon Prime": "amazonprime.svg",
    "Amazon RDS": "amazonrds.svg",
    "Amazon S3": "amazons3.svg",
    "Amazon SQS": "amazonsqs.svg",
    "AMD": "amd.svg",
    "American Airlines": "americanairlines.svg",
    "American Express": "americanexpress.svg",
    "AMG": "amg.svg",
    "AMP": "amp.svg",
    "Amul": "amul.svg",
    "ANA": "ana.svg",
    "Anaconda": "anaconda.svg",
    "Analogue": "analogue.svg",
    "Anchor": "anchor.svg",
    "Andela": "andela.svg",
    "Android": "android.svg",
    "Android Auto": "androidauto.svg",
    "Android Studio": "androidstudio.svg",
    "AngelList": "angellist.svg",
    "Angular": "angular.svg",
    "Angular Universal": "angularuniversal.svg",
    "AngularJS": "angularjs.svg",
    "AniList": "anilist.svg",
    "Ansible": "ansible.svg",
    "Ansys": "ansys.svg",
    "Ant Design": "antdesign.svg",
    "Anta": "anta.svg",
    "Antena 3": "antena3.svg",
    "AnyDesk": "anydesk.svg",
    "AOL": "aol.svg",
    "Apache": "apache.svg",
    "Apache Airflow": "apacheairflow.svg",
    "Apache Ant": "apacheant.svg",
    "Apache Cassandra": "apachecassandra.svg",
    "Apache CloudStack": "apachecloudstack.svg",
    "Apache Cordova": "apachecordova.svg",
    "Apache CouchDB": "apachecouchdb.svg",
    "Apache Druid": "apachedruid.svg",
    "Apache ECharts": "apacheecharts.svg",
    "Apache Flink": "apacheflink.svg",
    "Apache Groovy": "apachegroovy.svg",
    "Apache Hadoop": "apachehadoop.svg",
    "Apache Hive": "apachehive.svg",
    "Apache JMeter": "apachejmeter.svg",
    "Apache Kafka": "apachekafka.svg",
    "Apache Kylin": "apachekylin.svg",
    "Apache Maven": "apachemaven.svg",
    "Apache NetBeans IDE": "apachenetbeanside.svg",
    "Apache OpenOffice": "apacheopenoffice.svg",
    "Apache Pulsar": "apachepulsar.svg",
    "Apache RocketMQ": "apacherocketmq.svg",
    "Apache Solr": "apachesolr.svg",
    "Apache Spark": "apachespark.svg",
    "Apache Tomcat": "apachetomcat.svg",
    "Aparat": "aparat.svg",
    "Apollo GraphQL": "apollographql.svg",
    "Apostrophe": "apostrophe.svg",
    "App Store": "appstore.svg",
    "Appian": "appian.svg",
    "Apple": "apple.svg",
    "Apple Arcade": "applearcade.svg",
    "Apple Music": "applemusic.svg",
    "Apple News": "applenews.svg",
    "Apple Pay": "applepay.svg",
    "Apple Podcasts": "applepodcasts.svg",
    "Apple TV": "appletv.svg",
    "AppSignal": "appsignal.svg",
    "AppVeyor": "appveyor.svg",
    "Appwrite": "appwrite.svg",
    "Aqua": "aqua.svg",
    "ARAL": "aral.svg",
    "ArangoDB": "arangodb.svg",
    "Arch Linux": "archlinux.svg",
    "Archicad": "archicad.svg",
    "Archive of Our Own": "archiveofourown.svg",
    "Ardour": "ardour.svg",
    "Arduino": "arduino.svg",
    "Argo": "argo.svg",
    "Argos": "argos.svg",
    "ARK Ecosystem": "arkecosystem.svg",
    "Arlo": "arlo.svg",
    "Arm": "arm.svg",
    "Artifact Hub": "artifacthub.svg",
    "Artix Linux": "artixlinux.svg",
    "ArtStation": "artstation.svg",
    "arXiv": "arxiv.svg",
    "Asana": "asana.svg",
    "Asciidoctor": "asciidoctor.svg",
    "asciinema": "asciinema.svg",
    "ASDA": "asda.svg",
    "Aseprite": "aseprite.svg",
    "Ask Ubuntu": "askubuntu.svg",
    "ASKfm": "askfm.svg",
    "AssemblyScript": "assemblyscript.svg",
    "Aston Martin": "astonmartin.svg",
    "Astro": "astro.svg",
    "ASUS": "asus.svg",
    "AT&T": "atandt.svg",
    "Atari": "atari.svg",
    "Atlassian": "atlassian.svg",
    "Atom": "atom.svg",
    "Auchan": "auchan.svg",
    "Audacity": "audacity.svg",
    "Audi": "audi.svg",
    "Audible": "audible.svg",
    "Audio-Technica": "audiotechnica.svg",
    "Audioboom": "audioboom.svg",
    "Audiomack": "audiomack.svg",
    "Aurelia": "aurelia.svg",
    "Auth0": "auth0.svg",
    "Authy": "authy.svg",
    "Autodesk": "autodesk.svg",
    "AutoHotkey": "autohotkey.svg",
    "Automattic": "automattic.svg",
    "Autoprefixer": "autoprefixer.svg",
    "avajs": "avajs.svg",
    "Avast": "avast.svg",
    "Awesome Lists": "awesomelists.svg",
    "awesomeWM": "awesomewm.svg",
    "AWS Amplify": "awsamplify.svg",
    "AWS Fargate": "awsfargate.svg",
    "AWS Lambda": "awslambda.svg",
    "Axios": "axios.svg",
    "Azure Artifacts": "azureartifacts.svg",
    "Azure Data Explorer": "azuredataexplorer.svg",
    "Azure DevOps": "azuredevops.svg",
    "Azure Functions": "azurefunctions.svg",
    "Azure Pipelines": "azurepipelines.svg",
    "B&R Automation": "bandrautomation.svg",
    "Babel": "babel.svg",
    "Backblaze": "backblaze.svg",
    "Backbone.js": "backbonedotjs.svg",
    "Backendless": "backendless.svg",
    "Backstage": "backstage.svg",
    "Badgr": "badgr.svg",
    "Badoo": "badoo.svg",
    "Baidu": "baidu.svg",
    "Bamboo": "bamboo.svg",
    "Bandcamp": "bandcamp.svg",
    "BandLab": "bandlab.svg",
    "Bandsintown": "bandsintown.svg",
    "Bank of America": "bankofamerica.svg",
    "Barclays": "barclays.svg",
    "Baremetrics": "baremetrics.svg",
    "Basecamp": "basecamp.svg",
    "Bastyon": "bastyon.svg",
    "Bata": "bata.svg",
    "Bath ASU": "bathasu.svg",
    "Battle.net": "battledotnet.svg",
    "BBC": "bbc.svg",
    "BBC iPlayer": "bbciplayer.svg",
    "Beatport": "beatport.svg",
    "Beats": "beats.svg",
    "Beats by Dre": "beatsbydre.svg",
    "Behance": "behance.svg",
    "Beijing Subway": "beijingsubway.svg",
    "BEM": "bem.svg",
    "Bentley": "bentley.svg",
    "Betfair": "betfair.svg",
    "Big Cartel": "bigcartel.svg",
    "bigbasket": "bigbasket.svg",
    "BigBlueButton": "bigbluebutton.svg",
    "BigCommerce": "bigcommerce.svg",
    "Bilibili": "bilibili.svg",
    "Billboard": "billboard.svg",
    "BIM": "bim.svg",
    "Binance": "binance.svg",
    "Bio Link": "biolink.svg",
    "Bit": "bit.svg",
    "Bitbucket": "bitbucket.svg",
    "Bitcoin": "bitcoin.svg",
    "Bitcoin Cash": "bitcoincash.svg",
    "Bitcoin SV": "bitcoinsv.svg",
    "Bitdefender": "bitdefender.svg",
    "Bitly": "bitly.svg",
    "Bitrise": "bitrise.svg",
    "Bitwarden": "bitwarden.svg",
    "Bitwig": "bitwig.svg",
    "Blackberry": "blackberry.svg",
    "Blazemeter": "blazemeter.svg",
    "Blazor": "blazor.svg",
    "Blender": "blender.svg",
    "Blockchain.com": "blockchaindotcom.svg",
    "Blogger": "blogger.svg",
    "Bloglovin": "bloglovin.svg",
    "Blueprint": "blueprint.svg",
    "Bluetooth": "bluetooth.svg",
    "BMC Software": "bmcsoftware.svg",
    "BMW": "bmw.svg",
    "Boehringer Ingelheim": "boehringeringelheim.svg",
    "Boeing": "boeing.svg",
    "Bookalope": "bookalope.svg",
    "BookBub": "bookbub.svg",
    "Bookmeter": "bookmeter.svg",
    "BookMyShow": "bookmyshow.svg",
    "BookStack": "bookstack.svg",
    "Boost": "boost.svg",
    "Boots": "boots.svg",
    "Bootstrap": "bootstrap.svg",
    "BorgBackup": "borgbackup.svg",
    "Bosch": "bosch.svg",
    "Bose": "bose.svg",
    "boulanger": "boulanger.svg",
    "Bower": "bower.svg",
    "Box": "box.svg",
    "Boxy SVG": "boxysvg.svg",
    "Brandfolder": "brandfolder.svg",
    "Brave": "brave.svg",
    "Breaker": "breaker.svg",
    "British Airways": "britishairways.svg",
    "Broadcom": "broadcom.svg",
    "BT": "bt.svg",
    "Buddy": "buddy.svg",
    "Budibase": "budibase.svg",
    "Buefy": "buefy.svg",
    "Buffer": "buffer.svg",
    "Bugatti": "bugatti.svg",
    "Bugcrowd": "bugcrowd.svg",
    "Bugsnag": "bugsnag.svg",
    "Buildkite": "buildkite.svg",
    "Bukalapak": "bukalapak.svg",
    "Bulma": "bulma.svg",
    "Bun": "bun.svg",
    "bunq": "bunq.svg",
    "Burger King": "burgerking.svg",
    "Burton": "burton.svg",
    "Buy Me A Coffee": "buymeacoffee.svg",
    "BuzzFeed": "buzzfeed.svg",
    "Byju's": "byjus.svg",
    "byte": "byte.svg",
    "ByteDance": "bytedance.svg",
    "C": "c.svg",
    "C Sharp": "csharp.svg",
    "C++": "cplusplus.svg",
    "Cachet": "cachet.svg",
    "CafePress": "cafepress.svg",
    "Caffeine": "caffeine.svg",
    "Cairo Graphics": "cairographics.svg",
    "Cairo Metro": "cairometro.svg",
    "CakePHP": "cakephp.svg",
    "Campaign Monitor": "campaignmonitor.svg",
    "Canonical": "canonical.svg",
    "Canva": "canva.svg",
    "Capacitor": "capacitor.svg",
    "Car Throttle": "carthrottle.svg",
    "Carrefour": "carrefour.svg",
    "Carto": "carto.svg",
    "Cash App": "cashapp.svg",
    "Castbox": "castbox.svg",
    "Castorama": "castorama.svg",
    "Castro": "castro.svg",
    "Caterpillar": "caterpillar.svg",
    "CBS": "cbs.svg",
    "CD Projekt": "cdprojekt.svg",
    "Celery": "celery.svg",
    "CentOS": "centos.svg",
    "Ceph": "ceph.svg",
    "Cesium": "cesium.svg",
    "Chai": "chai.svg",
    "Chainlink": "chainlink.svg",
    "Chakra UI": "chakraui.svg",
    "Chart.js": "chartdotjs.svg",
    "ChartMogul": "chartmogul.svg",
    "Chase": "chase.svg",
    "ChatBot": "chatbot.svg",
    "CheckiO": "checkio.svg",
    "Checkmarx": "checkmarx.svg",
    "Chef": "chef.svg",
    "Chemex": "chemex.svg",
    "Chevrolet": "chevrolet.svg",
    "China Eastern Airlines": "chinaeasternairlines.svg",
    "China Southern Airlines": "chinasouthernairlines.svg",
    "Chocolatey": "chocolatey.svg",
    "Chromecast": "chromecast.svg",
    "Chrysler": "chrysler.svg",
    "Chupa Chups": "chupachups.svg",
    "Cilium": "cilium.svg",
    "Cinema 4D": "cinema4d.svg",
    "Circle": "circle.svg",
    "CircleCI": "circleci.svg",
    "Cirrus CI": "cirrusci.svg",
    "Cisco": "cisco.svg",
    "Citrix": "citrix.svg",
    "Citroën": "citroen.svg",
    "CiviCRM": "civicrm.svg",
    "Civo": "civo.svg",
    "CKEditor 4": "ckeditor4.svg",
    "Claris": "claris.svg",
    "ClickHouse": "clickhouse.svg",
    "ClickUp": "clickup.svg",
    "CLion": "clion.svg",
    "Cliqz": "cliqz.svg",
    "Clockify": "clockify.svg",
    "Clojure": "clojure.svg",
    "Cloud 66": "cloud66.svg",
    "Cloud Foundry": "cloudfoundry.svg",
    "CloudBees": "cloudbees.svg",
    "CloudCannon": "cloudcannon.svg",
    "Cloudera": "cloudera.svg",
    "Cloudflare": "cloudflare.svg",
    "Cloudflare Pages": "cloudflarepages.svg",
    "Cloudsmith": "cloudsmith.svg",
    "Cloudways": "cloudways.svg",
    "Clubhouse": "clubhouse.svg",
    "Clyp": "clyp.svg",
    "CMake": "cmake.svg",
    "CNCF": "cncf.svg",
    "CNN": "cnn.svg",
    "Co-op": "coop.svg",
    "Cockpit": "cockpit.svg",
    "Cockroach Labs": "cockroachlabs.svg",
    "CocoaPods": "cocoapods.svg",
    "Cocos": "cocos.svg",
    "Coda": "coda.svg",
    "Codacy": "codacy.svg",
    "Code Climate": "codeclimate.svg",
    "Code Review": "codereview.svg",
    "Codeberg": "codeberg.svg",
    "Codecademy": "codecademy.svg",
    "CodeceptJS": "codeceptjs.svg",
    "CodeChef": "codechef.svg",
    "Codecov": "codecov.svg",
    "CodeFactor": "codefactor.svg",
    "Codeforces": "codeforces.svg",
    "CodeIgniter": "codeigniter.svg",
    "Codemagic": "codemagic.svg",
    "CodeMirror": "codemirror.svg",
    "CodeNewbie": "codenewbie.svg",
    "CodePen": "codepen.svg",
    "CodeProject": "codeproject.svg",
    "CodersRank": "codersrank.svg",
    "Coderwall": "coderwall.svg",
    "CodeSandbox": "codesandbox.svg",
    "Codeship": "codeship.svg",
    "Codewars": "codewars.svg",
    "Coding Ninjas": "codingninjas.svg",
    "CodinGame": "codingame.svg",
    "Codio": "codio.svg",
    "CoffeeScript": "coffeescript.svg",
    "Cognizant": "cognizant.svg",
    "Coil": "coil.svg",
    "Coinbase": "coinbase.svg",
    "CoinMarketCap": "coinmarketcap.svg",
    "Commerzbank": "commerzbank.svg",
    "commitlint": "commitlint.svg",
    "Commodore": "commodore.svg",
    "Common Workflow Language": "commonworkflowlanguage.svg",
    "Composer": "composer.svg",
    "Comsol": "comsol.svg",
    "Conan": "conan.svg",
    "Concourse": "concourse.svg",
    "Conda-Forge": "condaforge.svg",
    "Conekta": "conekta.svg",
    "Confluence": "confluence.svg",
    "Construct 3": "construct3.svg",
    "Consul": "consul.svg",
    "Contactless Payment": "contactlesspayment.svg",
    "containerd": "containerd.svg",
    "Contentful": "contentful.svg",
    "Conventional Commits": "conventionalcommits.svg",
    "Convertio": "convertio.svg",
    "Cookiecutter": "cookiecutter.svg",
    "Cora": "cora.svg",
    "Corona Engine": "coronaengine.svg",
    "Corona Renderer": "coronarenderer.svg",
    "Corsair": "corsair.svg",
    "Couchbase": "couchbase.svg",
    "Counter-Strike": "counterstrike.svg",
    "CountingWorks PRO": "countingworkspro.svg",
    "Coursera": "coursera.svg",
    "Coveralls": "coveralls.svg",
    "cPanel": "cpanel.svg",
    "Craft CMS": "craftcms.svg",
    "CrateDB": "cratedb.svg",
    "Crayon": "crayon.svg",
    "Create React App": "createreactapp.svg",
    "Creative Commons": "creativecommons.svg",
    "Credly": "credly.svg",
    "Crehana": "crehana.svg",
    "Critical Role": "criticalrole.svg",
    "Crowdin": "crowdin.svg",
    "Crowdsource": "crowdsource.svg",
    "Crunchbase": "crunchbase.svg",
    "Crunchyroll": "crunchyroll.svg",
    "CRYENGINE": "cryengine.svg",
    "Crystal": "crystal.svg",
    "CSS Modules": "cssmodules.svg",
    "CSS Wizardry": "csswizardry.svg",
    "CSS3": "css3.svg",
    "Cucumber": "cucumber.svg",
    "curl": "curl.svg",
    "CurseForge": "curseforge.svg",
    "Cycling '74": "cycling74.svg",
    "Cypress": "cypress.svg",
    "Cytoscape.js": "cytoscapedotjs.svg",
    "D": "d.svg",
    "D-EDGE": "dedge.svg",
    "D-Wave Systems": "dwavesystems.svg",
    "D3.js": "d3dotjs.svg",
    "Dacia": "dacia.svg",
    "DAF": "daf.svg",
    "Dailymotion": "dailymotion.svg",
    "Daimler": "daimler.svg",
    "Dapr": "dapr.svg",
    "Dark Reader": "darkreader.svg",
    "Dart": "dart.svg",
    "Darty": "darty.svg",
    "Das Erste": "daserste.svg",
    "Dash": "dash.svg",
    "Dashlane": "dashlane.svg",
    "Dask": "dask.svg",
    "Dassault Systèmes": "dassaultsystemes.svg",
    "data.ai": "datadotai.svg",
    "Databricks": "databricks.svg",
    "DataCamp": "datacamp.svg",
    "Datadog": "datadog.svg",
    "DataGrip": "datagrip.svg",
    "Dataiku": "dataiku.svg",
    "DataStax": "datastax.svg",
    "Dataverse": "dataverse.svg",
    "DatoCMS": "datocms.svg",
    "Datto": "datto.svg",
    "DAZN": "dazn.svg",
    "dblp": "dblp.svg",
    "dbt": "dbt.svg",
    "DC Entertainment": "dcentertainment.svg",
    "De'Longhi": "delonghi.svg",
    "Debian": "debian.svg",
    "deepin": "deepin.svg",
    "Deepnote": "deepnote.svg",
    "Deezer": "deezer.svg",
    "del.icio.us": "delicious.svg",
    "Deliveroo": "deliveroo.svg",
    "Dell": "dell.svg",
    "Delphi": "delphi.svg",
    "Delta": "delta.svg",
    "Deno": "deno.svg",
    "Dependabot": "dependabot.svg",
    "Der Spiegel": "derspiegel.svg",
    "Designer News": "designernews.svg",
    "Deutsche Bahn": "deutschebahn.svg",
    "Deutsche Bank": "deutschebank.svg",
    "dev.to": "devdotto.svg",
    "DevExpress": "devexpress.svg",
    "DeviantArt": "deviantart.svg",
    "Devpost": "devpost.svg",
    "devRant": "devrant.svg",
    "Dgraph": "dgraph.svg",
    "DHL": "dhl.svg",
    "diagrams.net": "diagramsdotnet.svg",
    "Dialogflow": "dialogflow.svg",
    "Diaspora": "diaspora.svg",
    "Digg": "digg.svg",
    "Digi-Key Electronics": "digikeyelectronics.svg",
    "DigitalOcean": "digitalocean.svg",
    "Dior": "dior.svg",
    "Directus": "directus.svg",
    "Discogs": "discogs.svg",
    "Discord": "discord.svg",
    "Discourse": "discourse.svg",
    "Discover": "discover.svg",
    "Disqus": "disqus.svg",
    "Disroot": "disroot.svg",
    "Django": "django.svg",
    "Dlib": "dlib.svg",
    "DLNA": "dlna.svg",
    "dm": "dm.svg",
    "Docker": "docker.svg",
    "Docs.rs": "docsdotrs.svg",
    "DocuSign": "docusign.svg",
    "Dogecoin": "dogecoin.svg",
    "Dolby": "dolby.svg",
    "DoorDash": "doordash.svg",
    "Douban": "douban.svg",
    "Douban Read": "doubanread.svg",
    "Dovecot": "dovecot.svg",
    "DPD": "dpd.svg",
    "Dragonframe": "dragonframe.svg",
    "Draugiem.lv": "draugiemdotlv.svg",
    "Dribbble": "dribbble.svg",
    "Drone": "drone.svg",
    "Drooble": "drooble.svg",
    "Dropbox": "dropbox.svg",
    "Drupal": "drupal.svg",
    "DS Automobiles": "dsautomobiles.svg",
    "DTube": "dtube.svg",
    "Ducati": "ducati.svg",
    "DuckDB": "duckdb.svg",
    "DuckDuckGo": "duckduckgo.svg",
    "Dungeons & Dragons": "dungeonsanddragons.svg",
    "Dunked": "dunked.svg",
    "Duolingo": "duolingo.svg",
    "DVC": "dvc.svg",
    "dwm": "dwm.svg",
    "Dynamics 365": "dynamics365.svg",
    "Dynatrace": "dynatrace.svg",
    "E.Leclerc": "edotleclerc.svg",
    "E3": "e3.svg",
    "EA": "ea.svg",
    "Eagle": "eagle.svg",
    "easyJet": "easyjet.svg",
    "eBay": "ebay.svg",
    "Eclipse Che": "eclipseche.svg",
    "Eclipse IDE": "eclipseide.svg",
    "Eclipse Jetty": "eclipsejetty.svg",
    "Eclipse Mosquitto": "eclipsemosquitto.svg",
    "Eclipse Vert.x": "eclipsevertdotx.svg",
    "EDEKA": "edeka.svg",
    "EditorConfig": "editorconfig.svg",
    "edX": "edx.svg",
    "egghead": "egghead.svg",
    "Egnyte": "egnyte.svg",
    "Eight Sleep": "eightsleep.svg",
    "El Jueves": "eljueves.svg",
    "Elastic": "elastic.svg",
    "Elastic Cloud": "elasticcloud.svg",
    "Elastic Stack": "elasticstack.svg",
    "Elasticsearch": "elasticsearch.svg",
    "Electron": "electron.svg",
    "Electron Fiddle": "electronfiddle.svg",
    "electron-builder": "electronbuilder.svg",
    "Element": "element.svg",
    "elementary": "elementary.svg",
    "Elementor": "elementor.svg",
    "Eleventy": "eleventy.svg",
    "Elgato": "elgato.svg",
    "Elixir": "elixir.svg",
    "Ello": "ello.svg",
    "Elm": "elm.svg",
    "Elsevier": "elsevier.svg",
    "Embarcadero": "embarcadero.svg",
    "Ember.js": "emberdotjs.svg",
    "Emby": "emby.svg",
    "Emirates": "emirates.svg",
    "Emlakjet": "emlakjet.svg",
    "Empire Kred": "empirekred.svg",
    "Engadget": "engadget.svg",
    "Enpass": "enpass.svg",
    "EnterpriseDB": "enterprisedb.svg",
    "Envato": "envato.svg",
    "EPEL": "epel.svg",
    "Epic Games": "epicgames.svg",
    "Epson": "epson.svg",
    "Equinix Metal": "equinixmetal.svg",
    "Erlang": "erlang.svg",
    "esbuild": "esbuild.svg",
    "ESEA": "esea.svg",
    "ESLGaming": "eslgaming.svg",
    "ESLint": "eslint.svg",
    "ESPHome": "esphome.svg",
    "Espressif": "espressif.svg",
    "etcd": "etcd.svg",
    "Ethereum": "ethereum.svg",
    "Ethiopian Airlines": "ethiopianairlines.svg",
    "Etihad Airways": "etihadairways.svg",
    "Etsy": "etsy.svg",
    "Event Store": "eventstore.svg",
    "Eventbrite": "eventbrite.svg",
    "Evernote": "evernote.svg",
    "Exercism": "exercism.svg",
    "Exordo": "exordo.svg",
    "Exoscale": "exoscale.svg",
    "Expensify": "expensify.svg",
    "Experts Exchange": "expertsexchange.svg",
    "Expo": "expo.svg",
    "Express": "express.svg",
    "ExpressVPN": "expressvpn.svg",
    "EyeEm": "eyeem.svg",
    "F-Droid": "fdroid.svg",
    "F-Secure": "fsecure.svg",
    "F1": "f1.svg",
    "F5": "f5.svg",
    "Facebook": "facebook.svg",
    "Facebook Gaming": "facebookgaming.svg",
    "Facebook Live": "facebooklive.svg",
    "FACEIT": "faceit.svg",
    "Facepunch": "facepunch.svg",
    "Falcon": "falcon.svg",
    "FamPay": "fampay.svg",
    "Fandango": "fandango.svg",
    "Fandom": "fandom.svg",
    "Fanfou": "fanfou.svg",
    "Fantom": "fantom.svg",
    "FARFETCH": "farfetch.svg",
    "FastAPI": "fastapi.svg",
    "Fastify": "fastify.svg",
    "Fastlane": "fastlane.svg",
    "Fastly": "fastly.svg",
    "Fathom": "fathom.svg",
    "Fauna": "fauna.svg",
    "Favro": "favro.svg",
    "FeatHub": "feathub.svg",
    "FedEx": "fedex.svg",
    "Fedora": "fedora.svg",
    "Feedly": "feedly.svg",
    "Ferrari": "ferrari.svg",
    "Ferrari N.V.": "ferrarinv.svg",
    "FFmpeg": "ffmpeg.svg",
    "Fiat": "fiat.svg",
    "Fido Alliance": "fidoalliance.svg",
    "FIFA": "fifa.svg",
    "Figma": "figma.svg",
    "figshare": "figshare.svg",
    "Fila": "fila.svg",
    "Files": "files.svg",
    "FileZilla": "filezilla.svg",
    "Fing": "fing.svg",
    "Firebase": "firebase.svg",
    "Firefox": "firefox.svg",
    "Firefox Browser": "firefoxbrowser.svg",
    "Fireship": "fireship.svg",
    "Firewalla": "firewalla.svg",
    "FIRST": "first.svg",
    "Fitbit": "fitbit.svg",
    "FITE": "fite.svg",
    "FiveM": "fivem.svg",
    "Fiverr": "fiverr.svg",
    "Flask": "flask.svg",
    "Flat": "flat.svg",
    "Flathub": "flathub.svg",
    "Flatpak": "flatpak.svg",
    "Flattr": "flattr.svg",
    "Flickr": "flickr.svg",
    "Flipboard": "flipboard.svg",
    "Flipkart": "flipkart.svg",
    "Floatplane": "floatplane.svg",
    "Flood": "flood.svg",
    "Fluent Bit": "fluentbit.svg",
    "Fluentd": "fluentd.svg",
    "Flutter": "flutter.svg",
    "Flyway": "flyway.svg",
    "FMOD": "fmod.svg",
    "Fnac": "fnac.svg",
    "Folium": "folium.svg",
    "Fonoma": "fonoma.svg",
    "Font Awesome": "fontawesome.svg",
    "FontBase": "fontbase.svg",
    "foodpanda": "foodpanda.svg",
    "Ford": "ford.svg",
    "Forestry": "forestry.svg",
    "Formstack": "formstack.svg",
    "Fortinet": "fortinet.svg",
    "Fortran": "fortran.svg",
    "Fossa": "fossa.svg",
    "Fossil SCM": "fossilscm.svg",
    "Foursquare": "foursquare.svg",
    "Foursquare City Guide": "foursquarecityguide.svg",
    "FOX": "fox.svg",
    "Foxtel": "foxtel.svg",
    "Fozzy": "fozzy.svg",
    "Framer": "framer.svg",
    "Framework7": "framework7.svg",
    "Franprix": "franprix.svg",
    "Fraunhofer-Gesellschaft": "fraunhofergesellschaft.svg",
    "FreeBSD": "freebsd.svg",
    "freeCodeCamp": "freecodecamp.svg",
    "freedesktop.org": "freedesktopdotorg.svg",
    "Freelancer": "freelancer.svg",
    "FreeNAS": "freenas.svg",
    "Frontend Mentor": "frontendmentor.svg",
    "Fuga Cloud": "fugacloud.svg",
    "Fujifilm": "fujifilm.svg",
    "Fujitsu": "fujitsu.svg",
    "Funimation": "funimation.svg",
    "Fur Affinity": "furaffinity.svg",
    "Furry Network": "furrynetwork.svg",
    "FutureLearn": "futurelearn.svg",
    "G2": "g2.svg",
    "G2A": "g2a.svg",
    "Game & Watch": "gameandwatch.svg",
    "Game Developer": "gamedeveloper.svg",
    "Game Jolt": "gamejolt.svg",
    "Garmin": "garmin.svg",
    "Gatling": "gatling.svg",
    "Gatsby": "gatsby.svg",
    "Géant": "geant.svg",
    "GeeksforGeeks": "geeksforgeeks.svg",
    "General Electric": "generalelectric.svg",
    "General Motors": "generalmotors.svg",
    "Genius": "genius.svg",
    "Gentoo": "gentoo.svg",
    "Geocaching": "geocaching.svg",
    "Gerrit": "gerrit.svg",
    "Ghost": "ghost.svg",
    "Ghostery": "ghostery.svg",
    "GIMP": "gimp.svg",
    "GIPHY": "giphy.svg",
    "Git": "git.svg",
    "Git Extensions": "gitextensions.svg",
    "Git LFS": "gitlfs.svg",
    "GitBook": "gitbook.svg",
    "Gitea": "gitea.svg",
    "Gitee": "gitee.svg",
    "GitHub": "github.svg",
    "GitHub Actions": "githubactions.svg",
    "GitHub Pages": "githubpages.svg",
    "GitHub Sponsors": "githubsponsors.svg",
    "gitignore.io": "gitignoredotio.svg",
    "GitKraken": "gitkraken.svg",
    "GitLab": "gitlab.svg",
    "Gitpod": "gitpod.svg",
    "Gitter": "gitter.svg",
    "Glassdoor": "glassdoor.svg",
    "Glitch": "glitch.svg",
    "Globus": "globus.svg",
    "Gmail": "gmail.svg",
    "GNOME": "gnome.svg",
    "GNOME Terminal": "gnometerminal.svg",
    "GNU": "gnu.svg",
    "GNU Bash": "gnubash.svg",
    "GNU Emacs": "gnuemacs.svg",
    "GNU IceCat": "gnuicecat.svg",
    "GNU Privacy Guard": "gnuprivacyguard.svg",
    "GNU social": "gnusocial.svg",
    "Go": "go.svg",
    "GoCD": "gocd.svg",
    "GoDaddy": "godaddy.svg",
    "Godot Engine": "godotengine.svg",
    "GoFundMe": "gofundme.svg",
    "GOG.com": "gogdotcom.svg",
    "GoLand": "goland.svg",
    "GoldenLine": "goldenline.svg",
    "Goodreads": "goodreads.svg",
    "Google": "google.svg",
    "Google AdMob": "googleadmob.svg",
    "Google Ads": "googleads.svg",
    "Google AdSense": "googleadsense.svg",
    "Google Analytics": "googleanalytics.svg",
    "Google Assistant": "googleassistant.svg",
    "Google Calendar": "googlecalendar.svg",
    "Google Cardboard": "googlecardboard.svg",
    "Google Chat": "googlechat.svg",
    "Google Chrome": "googlechrome.svg",
    "Google Classroom": "googleclassroom.svg",
    "Google Cloud": "googlecloud.svg",
    "Google Colab": "googlecolab.svg",
    "Google Domains": "googledomains.svg",
    "Google Drive": "googledrive.svg",
    "Google Earth": "googleearth.svg",
    "Google Fit": "googlefit.svg",
    "Google Fonts": "googlefonts.svg",
    "Google Hangouts": "googlehangouts.svg",
    "Google Home": "googlehome.svg",
    "Google Keep": "googlekeep.svg",
    "Google Lens": "googlelens.svg",
    "Google Maps": "googlemaps.svg",
    "Google Marketing Platform": "googlemarketingplatform.svg",
    "Google Meet": "googlemeet.svg",
    "Google Messages": "googlemessages.svg",
    "Google My Business": "googlemybusiness.svg",
    "Google Nearby": "googlenearby.svg",
    "Google News": "googlenews.svg",
    "Google Optimize": "googleoptimize.svg",
    "Google Pay": "googlepay.svg",
    "Google Photos": "googlephotos.svg",
    "Google Play": "googleplay.svg",
    "Google Podcasts": "googlepodcasts.svg",
    "Google Scholar": "googlescholar.svg",
    "Google Search Console": "googlesearchconsole.svg",
    "Google Sheets": "googlesheets.svg",
    "Google Street View": "googlestreetview.svg",
    "Google Tag Manager": "googletagmanager.svg",
    "Google Translate": "googletranslate.svg",
    "GoToMeeting": "gotomeeting.svg",
    "Grab": "grab.svg",
    "Gradle": "gradle.svg",
    "Grafana": "grafana.svg",
    "Grammarly": "grammarly.svg",
    "Grand Frais": "grandfrais.svg",
    "GraphQL": "graphql.svg",
    "Grav": "grav.svg",
    "Gravatar": "gravatar.svg",
    "Graylog": "graylog.svg",
    "Greenhouse": "greenhouse.svg",
    "GreenSock": "greensock.svg",
    "Grid.ai": "griddotai.svg",
    "Gridsome": "gridsome.svg",
    "GroupMe": "groupme.svg",
    "Groupon": "groupon.svg",
    "Grubhub": "grubhub.svg",
    "Grunt": "grunt.svg",
    "GSK": "gsk.svg",
    "GTK": "gtk.svg",
    "Guangzhou Metro": "guangzhoumetro.svg",
    "Guilded": "guilded.svg",
    "gulp": "gulp.svg",
    "Gumroad": "gumroad.svg",
    "Gumtree": "gumtree.svg",
    "Gunicorn": "gunicorn.svg",
    "Gurobi": "gurobi.svg",
    "Gutenberg": "gutenberg.svg",
    "Habr": "habr.svg",
    "Hack Club": "hackclub.svg",
    "Hack The Box": "hackthebox.svg",
    "Hackaday": "hackaday.svg",
    "Hacker Noon": "hackernoon.svg",
    "HackerEarth": "hackerearth.svg",
    "HackerOne": "hackerone.svg",
    "HackerRank": "hackerrank.svg",
    "Hackster": "hackster.svg",
    "Handlebars.js": "handlebarsdotjs.svg",
    "Handshake": "handshake.svg",
    "Handshake": "handshake_protocol.svg",
    "HappyCow": "happycow.svg",
    "Harbor": "harbor.svg",
    "HarmonyOS": "harmonyos.svg",
    "Hashnode": "hashnode.svg",
    "Haskell": "haskell.svg",
    "Hasura": "hasura.svg",
    "Hatena Bookmark": "hatenabookmark.svg",
    "haveibeenpwned": "haveibeenpwned.svg",
    "Haxe": "haxe.svg",
    "HBO": "hbo.svg",
    "HCL": "hcl.svg",
    "Headless UI": "headlessui.svg",
    "Headspace": "headspace.svg",
    "Hedera": "hedera.svg",
    "HelloFresh": "hellofresh.svg",
    "Helly Hansen": "hellyhansen.svg",
    "Helm": "helm.svg",
    "Help Scout": "helpscout.svg",
    "HelpDesk": "helpdesk.svg",
    "HERE": "here.svg",
    "Heroku": "heroku.svg",
    "Hetzner": "hetzner.svg",
    "Hexo": "hexo.svg",
    "HEY": "hey.svg",
    "Hi Bob": "hibob.svg",
    "Hibernate": "hibernate.svg",
    "Hilton": "hilton.svg",
    "Hitachi": "hitachi.svg",
    "Hive": "hive.svg",
    "Hive": "hive_blockchain.svg",
    "Home Assistant": "homeassistant.svg",
    "Home Assistant Community Store": "homeassistantcommunitystore.svg",
    "HomeAdvisor": "homeadvisor.svg",
    "Homebrew": "homebrew.svg",
    "Homebridge": "homebridge.svg",
    "homify": "homify.svg",
    "Honda": "honda.svg",
    "Honey": "honey.svg",
    "Hootsuite": "hootsuite.svg",
    "Hoppscotch": "hoppscotch.svg",
    "Hotels.com": "hotelsdotcom.svg",
    "Hotjar": "hotjar.svg",
    "Houdini": "houdini.svg",
    "Houzz": "houzz.svg",
    "HP": "hp.svg",
    "HTML Academy": "htmlacademy.svg",
    "HTML5": "html5.svg",
    "HTTPie": "httpie.svg",
    "Huawei": "huawei.svg",
    "HubSpot": "hubspot.svg",
    "Hugo": "hugo.svg",
    "Hulu": "hulu.svg",
    "Humble Bundle": "humblebundle.svg",
    "Hungry Jack's": "hungryjacks.svg",
    "Hurriyetemlak": "hurriyetemlak.svg",
    "Husqvarna": "husqvarna.svg",
    "Hyper": "hyper.svg",
    "Hyperledger": "hyperledger.svg",
    "Hypothesis": "hypothesis.svg",
    "Hyundai": "hyundai.svg",
    "i18next": "i18next.svg",
    "Iata": "iata.svg",
    "iBeacon": "ibeacon.svg",
    "IBM": "ibm.svg",
    "IBM Cloud": "ibmcloud.svg",
    "IBM Watson": "ibmwatson.svg",
    "Iced": "iced.svg",
    "Iceland": "iceland.svg",
    "Icinga": "icinga.svg",
    "iCloud": "icloud.svg",
    "IcoMoon": "icomoon.svg",
    "ICON": "icon.svg",
    "Iconfinder": "iconfinder.svg",
    "Iconify": "iconify.svg",
    "IconJar": "iconjar.svg",
    "Icons8": "icons8.svg",
    "ICQ": "icq.svg",
    "IEEE": "ieee.svg",
    "iFixit": "ifixit.svg",
    "iFood": "ifood.svg",
    "IFTTT": "ifttt.svg",
    "iHeartRadio": "iheartradio.svg",
    "IKEA": "ikea.svg",
    "ImageJ": "imagej.svg",
    "IMDb": "imdb.svg",
    "Imgur": "imgur.svg",
    "Immer": "immer.svg",
    "Imou": "imou.svg",
    "Indeed": "indeed.svg",
    "Infiniti": "infiniti.svg",
    "InfluxDB": "influxdb.svg",
    "Informatica": "informatica.svg",
    "Infosys": "infosys.svg",
    "Ingress": "ingress.svg",
    "Inkdrop": "inkdrop.svg",
    "Inkscape": "inkscape.svg",
    "Insomnia": "insomnia.svg",
    "Instacart": "instacart.svg",
    "Instagram": "instagram.svg",
    "Instapaper": "instapaper.svg",
    "Instatus": "instatus.svg",
    "Instructables": "instructables.svg",
    "Instructure": "instructure.svg",
    "Integromat": "integromat.svg",
    "Intel": "intel.svg",
    "IntelliJ IDEA": "intellijidea.svg",
    "Interaction Design Foundation": "interactiondesignfoundation.svg",
    "InteractJS": "interactjs.svg",
    "Intercom": "intercom.svg",
    "Intermarche": "intermarche.svg",
    "Internet Archive": "internetarchive.svg",
    "Internet Explorer": "internetexplorer.svg",
    "Intigriti": "intigriti.svg",
    "InVision": "invision.svg",
    "Invoice Ninja": "invoiceninja.svg",
    "ioBroker": "iobroker.svg",
    "Ionic": "ionic.svg",
    "Ionos": "ionos.svg",
    "iOS": "ios.svg",
    "IOTA": "iota.svg",
    "IPFS": "ipfs.svg",
    "Issuu": "issuu.svg",
    "Istio": "istio.svg",
    "Itch.io": "itchdotio.svg",
    "iTerm2": "iterm2.svg",
    "iTunes": "itunes.svg",
    "IVECO": "iveco.svg",
    "Jabber": "jabber.svg",
    "Jaguar": "jaguar.svg",
    "Jamboard": "jamboard.svg",
    "Jameson": "jameson.svg",
    "Jamstack": "jamstack.svg",
    "Jasmine": "jasmine.svg",
    "JavaScript": "javascript.svg",
    "JBL": "jbl.svg",
    "JCB": "jcb.svg",
    "Jeep": "jeep.svg",
    "Jekyll": "jekyll.svg",
    "Jellyfin": "jellyfin.svg",
    "Jenkins": "jenkins.svg",
    "Jenkins X": "jenkinsx.svg",
    "Jest": "jest.svg",
    "JET": "jet.svg",
    "JetBrains": "jetbrains.svg",
    "Jetpack Compose": "jetpackcompose.svg",
    "JFrog": "jfrog.svg",
    "JFrog Bintray": "jfrogbintray.svg",
    "Jinja": "jinja.svg",
    "Jira": "jira.svg",
    "Jira Software": "jirasoftware.svg",
    "Jitsi": "jitsi.svg",
    "John Deere": "johndeere.svg",
    "Joomla": "joomla.svg",
    "Joplin": "joplin.svg",
    "Jordan": "jordan.svg",
    "JPEG": "jpeg.svg",
    "jQuery": "jquery.svg",
    "JR Group": "jrgroup.svg",
    "jsDelivr": "jsdelivr.svg",
    "JSFiddle": "jsfiddle.svg",
    "JSON": "json.svg",
    "JSON Web Tokens": "jsonwebtokens.svg",
    "JSS": "jss.svg",
    "JUKE": "juke.svg",
    "Julia": "julia.svg",
    "Juniper Networks": "junipernetworks.svg",
    "JUnit5": "junit5.svg",
    "Jupyter": "jupyter.svg",
    "Just Eat": "justeat.svg",
    "JustGiving": "justgiving.svg",
    "K3s": "k3s.svg",
    "k6": "k6.svg",
    "Kaggle": "kaggle.svg",
    "Kahoot!": "kahoot.svg",
    "KaiOS": "kaios.svg",
    "Kakao": "kakao.svg",
    "KakaoTalk": "kakaotalk.svg",
    "Kali Linux": "kalilinux.svg",
    "Kaniko": "kaniko.svg",
    "Karlsruher Verkehrsverbund": "karlsruherverkehrsverbund.svg",
    "Kasa Smart": "kasasmart.svg",
    "KashFlow": "kashflow.svg",
    "Kaspersky": "kaspersky.svg",
    "Katacoda": "katacoda.svg",
    "Katana": "katana.svg",
    "Kaufland": "kaufland.svg",
    "KDE": "kde.svg",
    "Kdenlive": "kdenlive.svg",
    "Keep a Changelog": "keepachangelog.svg",
    "KeePassXC": "keepassxc.svg",
    "Kentico": "kentico.svg",
    "Keras": "keras.svg",
    "Keybase": "keybase.svg",
    "KeyCDN": "keycdn.svg",
    "Keystone": "keystone.svg",
    "KFC": "kfc.svg",
    "Khan Academy": "khanacademy.svg",
    "Khronos Group": "khronosgroup.svg",
    "Kia": "kia.svg",
    "Kibana": "kibana.svg",
    "KiCad": "kicad.svg",
    "Kickstarter": "kickstarter.svg",
    "Kik": "kik.svg",
    "Kingston Technology": "kingstontechnology.svg",
    "KinoPoisk": "kinopoisk.svg",
    "Kirby": "kirby.svg",
    "Kitsu": "kitsu.svg",
    "Klarna": "klarna.svg",
    "KLM": "klm.svg",
    "Klook": "klook.svg",
    "Knative": "knative.svg",
    "KnowledgeBase": "knowledgebase.svg",
    "Known": "known.svg",
    "Ko-fi": "kofi.svg",
    "Koa": "koa.svg",
    "Koc": "koc.svg",
    "Kodi": "kodi.svg",
    "Kofax": "kofax.svg",
    "Komoot": "komoot.svg",
    "Konami": "konami.svg",
    "Kong": "kong.svg",
    "Kongregate": "kongregate.svg",
    "Konva": "konva.svg",
    "Kotlin": "kotlin.svg",
    "Koyeb": "koyeb.svg",
    "Krita": "krita.svg",
    "KTM": "ktm.svg",
    "Kuaishou": "kuaishou.svg",
    "Kubernetes": "kubernetes.svg",
    "Kubuntu": "kubuntu.svg",
    "Kuma": "kuma.svg",
    "Kuula": "kuula.svg",
    "Kyocera": "kyocera.svg",
    "LabVIEW": "labview.svg",
    "Lada": "lada.svg",
    "Lamborghini": "lamborghini.svg",
    "Land Rover": "landrover.svg",
    "Lapce": "lapce.svg",
    "Laragon": "laragon.svg",
    "Laravel": "laravel.svg",
    "Laravel Horizon": "laravelhorizon.svg",
    "Laravel Nova": "laravelnova.svg",
    "Last.fm": "lastdotfm.svg",
    "LastPass": "lastpass.svg",
    "LaTeX": "latex.svg",
    "Launchpad": "launchpad.svg",
    "Lazarus": "lazarus.svg",
    "LBRY": "lbry.svg",
    "Leader Price": "leaderprice.svg",
    "Leaflet": "leaflet.svg",
    "Leanpub": "leanpub.svg",
    "LeetCode": "leetcode.svg",
    "Legacy Games": "legacygames.svg",
    "Lemmy": "lemmy.svg",
    "Lenovo": "lenovo.svg",
    "Lens": "lens.svg",
    "Lerna": "lerna.svg",
    "Leroy Merlin": "leroymerlin.svg",
    "Less": "less.svg",
    "Let's Encrypt": "letsencrypt.svg",
    "Letterboxd": "letterboxd.svg",
    "levels.fyi": "levelsdotfyi.svg",
    "LG": "lg.svg",
    "LGTM": "lgtm.svg",
    "Liberapay": "liberapay.svg",
    "Libraries.io": "librariesdotio.svg",
    "LibraryThing": "librarything.svg",
    "LibreOffice": "libreoffice.svg",
    "libuv": "libuv.svg",
    "Lichess": "lichess.svg",
    "Lidl": "lidl.svg",
    "LIFX": "lifx.svg",
    "Lighthouse": "lighthouse.svg",
    "LINE": "line.svg",
    "LineageOS": "lineageos.svg",
    "Linear": "linear.svg",
    "LinkedIn": "linkedin.svg",
    "Linkerd": "linkerd.svg",
    "Linkfire": "linkfire.svg",
    "Linktree": "linktree.svg",
    "Linode": "linode.svg",
    "Linux": "linux.svg",
    "Linux Containers": "linuxcontainers.svg",
    "Linux Foundation": "linuxfoundation.svg",
    "Linux Mint": "linuxmint.svg",
    "Lion Air": "lionair.svg",
    "Liquibase": "liquibase.svg",
    "Lit": "lit.svg",
    "Litecoin": "litecoin.svg",
    "LITIENGINE": "litiengine.svg",
    "LiveChat": "livechat.svg",
    "LiveJournal": "livejournal.svg",
    "Livewire": "livewire.svg",
    "LLVM": "llvm.svg",
    "LMMS": "lmms.svg",
    "Lodash": "lodash.svg",
    "Logitech": "logitech.svg",
    "LogMeIn": "logmein.svg",
    "Logstash": "logstash.svg",
    "Looker": "looker.svg",
    "Loom": "loom.svg",
    "Loop": "loop.svg",
    "LoopBack": "loopback.svg",
    "Lospec": "lospec.svg",
    "LOT Polish Airlines": "lotpolishairlines.svg",
    "Lua": "lua.svg",
    "Lubuntu": "lubuntu.svg",
    "Ludwig": "ludwig.svg",
    "Lufthansa": "lufthansa.svg",
    "Lumen": "lumen.svg",
    "Lunacy": "lunacy.svg",
    "Lydia": "lydia.svg",
    "Lyft": "lyft.svg",
    "MAAS": "maas.svg",
    "macOS": "macos.svg",
    "MacPaw": "macpaw.svg",
    "Macy's": "macys.svg",
    "Magasins U": "magasinsu.svg",
    "Magento": "magento.svg",
    "Magisk": "magisk.svg",
    "Mail.Ru": "maildotru.svg",
    "MailChimp": "mailchimp.svg",
    "Mailgun": "mailgun.svg",
    "Major League Hacking": "majorleaguehacking.svg",
    "MakerBot": "makerbot.svg",
    "MAMP": "mamp.svg",
    "MAN": "man.svg",
    "ManageIQ": "manageiq.svg",
    "Manjaro": "manjaro.svg",
    "Mapbox": "mapbox.svg",
    "MariaDB": "mariadb.svg",
    "MariaDB Foundation": "mariadbfoundation.svg",
    "Markdown": "markdown.svg",
    "Marketo": "marketo.svg",
    "Marko": "marko.svg",
    "Marriott": "marriott.svg",
    "Maserati": "maserati.svg",
    "MasterCard": "mastercard.svg",
    "mastercomfig": "mastercomfig.svg",
    "Mastodon": "mastodon.svg",
    "Material Design": "materialdesign.svg",
    "Material Design Icons": "materialdesignicons.svg",
    "Matomo": "matomo.svg",
    "Matrix": "matrix.svg",
    "Matter.js": "matterdotjs.svg",
    "Mattermost": "mattermost.svg",
    "Matternet": "matternet.svg",
    "Max": "max.svg",
    "Max-Planck-Gesellschaft": "maxplanckgesellschaft.svg",
    "Maytag": "maytag.svg",
    "Mazda": "mazda.svg",
    "McAfee": "mcafee.svg",
    "McDonald's": "mcdonalds.svg",
    "McLaren": "mclaren.svg",
    "mdBook": "mdbook.svg",
    "MDN Web Docs": "mdnwebdocs.svg",
    "MDX": "mdx.svg",
    "MediaFire": "mediafire.svg",
    "MediaMarkt": "mediamarkt.svg",
    "MediaTek": "mediatek.svg",
    "MediaTemple": "mediatemple.svg",
    "Medium": "medium.svg",
    "Meetup": "meetup.svg",
    "MEGA": "mega.svg",
    "Mendeley": "mendeley.svg",
    "Mercedes": "mercedes.svg",
    "Merck": "merck.svg",
    "Mercurial": "mercurial.svg",
    "Messenger": "messenger.svg",
    "Meta": "meta.svg",
    "Metabase": "metabase.svg",
    "MetaFilter": "metafilter.svg",
    "Meteor": "meteor.svg",
    "Metro": "metro.svg",
    "Metro de la Ciudad de México": "metrodelaciudaddemexico.svg",
    "Metro de Madrid": "metrodemadrid.svg",
    "Métro de Paris": "metrodeparis.svg",
    "MeWe": "mewe.svg",
    "micro:bit": "microbit.svg",
    "Micro.blog": "microdotblog.svg",
    "Microgenetics": "microgenetics.svg",
    "MicroPython": "micropython.svg",
    "Microsoft": "microsoft.svg",
    "Microsoft Academic": "microsoftacademic.svg",
    "Microsoft Access": "microsoftaccess.svg",
    "Microsoft Azure": "microsoftazure.svg",
    "Microsoft Bing": "microsoftbing.svg",
    "Microsoft Edge": "microsoftedge.svg",
    "Microsoft Excel": "microsoftexcel.svg",
    "Microsoft Exchange": "microsoftexchange.svg",
    "Microsoft Office": "microsoftoffice.svg",
    "Microsoft OneDrive": "microsoftonedrive.svg",
    "Microsoft OneNote": "microsoftonenote.svg",
    "Microsoft Outlook": "microsoftoutlook.svg",
    "Microsoft PowerPoint": "microsoftpowerpoint.svg",
    "Microsoft SharePoint": "microsoftsharepoint.svg",
    "Microsoft SQL Server": "microsoftsqlserver.svg",
    "Microsoft Teams": "microsoftteams.svg",
    "Microsoft Translator": "microsofttranslator.svg",
    "Microsoft Visio": "microsoftvisio.svg",
    "Microsoft Word": "microsoftword.svg",
    "MicroStrategy": "microstrategy.svg",
    "MIDI": "midi.svg",
    "Minds": "minds.svg",
    "Minecraft": "minecraft.svg",
    "Minetest": "minetest.svg",
    "Mini": "mini.svg",
    "Minutemailer": "minutemailer.svg",
    "Miro": "miro.svg",
    "Mitsubishi": "mitsubishi.svg",
    "Mix": "mix.svg",
    "Mixcloud": "mixcloud.svg",
    "MLB": "mlb.svg",
    "MLflow": "mlflow.svg",
    "MobX": "mobx.svg",
    "MobX-State-Tree": "mobxstatetree.svg",
    "Mocha": "mocha.svg",
    "MODX": "modx.svg",
    "Mojang Studios": "mojangstudios.svg",
    "Moleculer": "moleculer.svg",
    "Momenteo": "momenteo.svg",
    "Monero": "monero.svg",
    "MoneyGram": "moneygram.svg",
    "MongoDB": "mongodb.svg",
    "monkey tie": "monkeytie.svg",
    "MonoGames": "monogames.svg",
    "Monoprix": "monoprix.svg",
    "Monster": "monster.svg",
    "Monzo": "monzo.svg",
    "Moo": "moo.svg",
    "Moonrepo": "moonrepo.svg",
    "Morrisons": "morrisons.svg",
    "Moscow Metro": "moscowmetro.svg",
    "Motorola": "motorola.svg",
    "Mozilla": "mozilla.svg",
    "MQTT": "mqtt.svg",
    "MSI": "msi.svg",
    "MSI Business": "msibusiness.svg",
    "MTA": "mta.svg",
    "MTR": "mtr.svg",
    "MUI": "mui.svg",
    "Mulesoft": "mulesoft.svg",
    "Müller": "muller.svg",
    "Mumble": "mumble.svg",
    "MuseScore": "musescore.svg",
    "MusicBrainz": "musicbrainz.svg",
    "MX Linux": "mxlinux.svg",
    "MyAnimeList": "myanimelist.svg",
    "MYOB": "myob.svg",
    "Myspace": "myspace.svg",
    "MySQL": "mysql.svg",
    "N26": "n26.svg",
    "Namebase": "namebase.svg",
    "Namecheap": "namecheap.svg",
    "Nano": "nano.svg",
    "NASA": "nasa.svg",
    "National Grid": "nationalgrid.svg",
    "NativeScript": "nativescript.svg",
    "Naver": "naver.svg",
    "NBA": "nba.svg",
    "NBB": "nbb.svg",
    "NDR": "ndr.svg",
    "NEC": "nec.svg",
    "Neo4j": "neo4j.svg",
    "Neovim": "neovim.svg",
    "NestJS": "nestjs.svg",
    "NetApp": "netapp.svg",
    "NetBSD": "netbsd.svg",
    "Netflix": "netflix.svg",
    "Netlify": "netlify.svg",
    "Nette": "nette.svg",
    "Netto": "netto.svg",
    "Neutralinojs": "neutralinojs.svg",
    "New Balance": "newbalance.svg",
    "New Japan Pro-Wrestling": "newjapanprowrestling.svg",
    "New Relic": "newrelic.svg",
    "New York Times": "newyorktimes.svg",
    "Next.js": "nextdotjs.svg",
    "NextBillion.ai": "nextbilliondotai.svg",
    "Nextcloud": "nextcloud.svg",
    "Nextdoor": "nextdoor.svg",
    "NFC": "nfc.svg",
    "NGINX": "nginx.svg",
    "ngrok": "ngrok.svg",
    "niconico": "niconico.svg",
    "Nike": "nike.svg",
    "Nim": "nim.svg",
    "Nintendo": "nintendo.svg",
    "Nintendo 3DS": "nintendo3ds.svg",
    "Nintendo GameCube": "nintendogamecube.svg",
    "Nintendo Network": "nintendonetwork.svg",
    "Nintendo Switch": "nintendoswitch.svg",
    "Nissan": "nissan.svg",
    "NixOS": "nixos.svg",
    "Node-RED": "nodered.svg",
    "Node.js": "nodedotjs.svg",
    "Nodemon": "nodemon.svg",
    "Nokia": "nokia.svg",
    "Norco": "norco.svg",
    "NordVPN": "nordvpn.svg",
    "Norwegian": "norwegian.svg",
    "Notepad++": "notepadplusplus.svg",
    "Notion": "notion.svg",
    "Notist": "notist.svg",
    "Noun Project": "nounproject.svg",
    "NOW": "now.svg",
    "npm": "npm.svg",
    "Nrwl": "nrwl.svg",
    "Nubank": "nubank.svg",
    "Nucleo": "nucleo.svg",
    "NuGet": "nuget.svg",
    "Nuke": "nuke.svg",
    "Numba": "numba.svg",
    "NumPy": "numpy.svg",
    "Nunjucks": "nunjucks.svg",
    "Nutanix": "nutanix.svg",
    "Nuxt.js": "nuxtdotjs.svg",
    "NVIDIA": "nvidia.svg",
    "Nx": "nx.svg",
    "NZXT": "nzxt.svg",
    "O'Reilly": "oreilly.svg",
    "OBS Studio": "obsstudio.svg",
    "Observable": "observable.svg",
    "Obsidian": "obsidian.svg",
    "OCaml": "ocaml.svg",
    "Octane Render": "octanerender.svg",
    "Octave": "octave.svg",
    "OctoPrint": "octoprint.svg",
    "Octopus Deploy": "octopusdeploy.svg",
    "Oculus": "oculus.svg",
    "Odnoklassniki": "odnoklassniki.svg",
    "Odysee": "odysee.svg",
    "Oh Dear": "ohdear.svg",
    "okcupid": "okcupid.svg",
    "Okta": "okta.svg",
    "OnePlus": "oneplus.svg",
    "OnlyFans": "onlyfans.svg",
    "ONLYOFFICE": "onlyoffice.svg",
    "ONNX": "onnx.svg",
    "OnStar": "onstar.svg",
    "Opel": "opel.svg",
    "Open Access": "openaccess.svg",
    "Open Badges": "openbadges.svg",
    "Open Bug Bounty": "openbugbounty.svg",
    "Open Collective": "opencollective.svg",
    "Open Containers Initiative": "opencontainersinitiative.svg",
    "Open Source Initiative": "opensourceinitiative.svg",
    "OpenAI": "openai.svg",
    "OpenAI Gym": "openaigym.svg",
    "OpenAPI Initiative": "openapiinitiative.svg",
    "OpenBSD": "openbsd.svg",
    "OpenCV": "opencv.svg",
    "OpenFaaS": "openfaas.svg",
    "OpenGL": "opengl.svg",
    "OpenID": "openid.svg",
    "OpenJDK": "openjdk.svg",
    "Openlayers": "openlayers.svg",
    "OpenMined": "openmined.svg",
    "OpenNebula": "opennebula.svg",
    "OpenProject": "openproject.svg",
    "OpenSea": "opensea.svg",
    "OpenSearch": "opensearch.svg",
    "OpenSSL": "openssl.svg",
    "OpenStack": "openstack.svg",
    "OpenStreetMap": "openstreetmap.svg",
    "openSUSE": "opensuse.svg",
    "OpenTelemetry": "opentelemetry.svg",
    "Openverse": "openverse.svg",
    "OpenVPN": "openvpn.svg",
    "OpenWrt": "openwrt.svg",
    "OpenZeppelin": "openzeppelin.svg",
    "OpenZFS": "openzfs.svg",
    "Opera": "opera.svg",
    "OPNSense": "opnsense.svg",
    "Opsgenie": "opsgenie.svg",
    "OpsLevel": "opslevel.svg",
    "Oracle": "oracle.svg",
    "ORCID": "orcid.svg",
    "Org": "org.svg",
    "Origin": "origin.svg",
    "Osano": "osano.svg",
    "Oshkosh": "oshkosh.svg",
    "OSMC": "osmc.svg",
    "osu!": "osu.svg",
    "Otto": "otto.svg",
    "Overcast": "overcast.svg",
    "Overleaf": "overleaf.svg",
    "OVH": "ovh.svg",
    "OWASP": "owasp.svg",
    "Oxygen": "oxygen.svg",
    "OYO": "oyo.svg",
    "p5.js": "p5dotjs.svg",
    "Packagist": "packagist.svg",
    "Packer": "packer.svg",
    "Paddy Power": "paddypower.svg",
    "Pagekit": "pagekit.svg",
    "PagerDuty": "pagerduty.svg",
    "PageSpeed Insights": "pagespeedinsights.svg",
    "PagSeguro": "pagseguro.svg",
    "Palantir": "palantir.svg",
    "Palo Alto Software": "paloaltosoftware.svg",
    "pandas": "pandas.svg",
    "Pandora": "pandora.svg",
    "Pantheon": "pantheon.svg",
    "Paperspace": "paperspace.svg",
    "Parity Substrate": "paritysubstrate.svg",
    "Parse.ly": "parsedotly.svg",
    "Passport": "passport.svg",
    "Pastebin": "pastebin.svg",
    "Patreon": "patreon.svg",
    "Payoneer": "payoneer.svg",
    "PayPal": "paypal.svg",
    "Paytm": "paytm.svg",
    "PCGamingWiki": "pcgamingwiki.svg",
    "Peak Design": "peakdesign.svg",
    "PeerTube": "peertube.svg",
    "Pegasus Airlines": "pegasusairlines.svg",
    "Pelican": "pelican.svg",
    "Peloton": "peloton.svg",
    "Penny": "penny.svg",
    "Penpot": "penpot.svg",
    "Pepsi": "pepsi.svg",
    "Percy": "percy.svg",
    "Perforce": "perforce.svg",
    "Perl": "perl.svg",
    "Persistent": "persistent.svg",
    "Personio": "personio.svg",
    "Pets at Home": "petsathome.svg",
    "Peugeot": "peugeot.svg",
    "Pexels": "pexels.svg",
    "pfSense": "pfsense.svg",
    "Phabricator": "phabricator.svg",
    "Philips Hue": "philipshue.svg",
    "PhonePe": "phonepe.svg",
    "Photobucket": "photobucket.svg",
    "Photocrowd": "photocrowd.svg",
    "Photopea": "photopea.svg",
    "PHP": "php.svg",
    "phpMyAdmin": "phpmyadmin.svg",
    "PhpStorm": "phpstorm.svg",
    "Pi-hole": "pihole.svg",
    "Picard Surgelés": "picardsurgeles.svg",
    "Picarto.TV": "picartodottv.svg",
    "Picnic": "picnic.svg",
    "PicPay": "picpay.svg",
    "Pimcore": "pimcore.svg",
    "Pinboard": "pinboard.svg",
    "Pingdom": "pingdom.svg",
    "Pinterest": "pinterest.svg",
    "Pioneer DJ": "pioneerdj.svg",
    "Pivotal Tracker": "pivotaltracker.svg",
    "Piwigo": "piwigo.svg",
    "Pix": "pix.svg",
    "Pixabay": "pixabay.svg",
    "pixiv": "pixiv.svg",
    "pkgsrc": "pkgsrc.svg",
    "Planet": "planet.svg",
    "PlanetScale": "planetscale.svg",
    "PlanGrid": "plangrid.svg",
    "Platform.sh": "platformdotsh.svg",
    "Platzi": "platzi.svg",
    "Plausible Analytics": "plausibleanalytics.svg",
    "PlayCanvas": "playcanvas.svg",
    "Player FM": "playerfm.svg",
    "Player.me": "playerdotme.svg",
    "PlayStation": "playstation.svg",
    "PlayStation 2": "playstation2.svg",
    "PlayStation 3": "playstation3.svg",
    "PlayStation 4": "playstation4.svg",
    "PlayStation 5": "playstation5.svg",
    "PlayStation Vita": "playstationvita.svg",
    "Playwright": "playwright.svg",
    "Pleroma": "pleroma.svg",
    "Plesk": "plesk.svg",
    "Plex": "plex.svg",
    "Plotly": "plotly.svg",
    "Pluralsight": "pluralsight.svg",
    "Plurk": "plurk.svg",
    "Plus Codes": "pluscodes.svg",
    "PM2": "pm2.svg",
    "pnpm": "pnpm.svg",
    "Pocket": "pocket.svg",
    "Pocket Casts": "pocketcasts.svg",
    "PocketBase": "pocketbase.svg",
    "Podcast Addict": "podcastaddict.svg",
    "Podman": "podman.svg",
    "Poetry": "poetry.svg",
    "Pointy": "pointy.svg",
    "Pokémon": "pokemon.svg",
    "Polkadot": "polkadot.svg",
    "Poly": "poly.svg",
    "Polymer Project": "polymerproject.svg",
    "Polywork": "polywork.svg",
    "Pop!_OS": "popos.svg",
    "Porsche": "porsche.svg",
    "Portainer": "portainer.svg",
    "PostCSS": "postcss.svg",
    "PostgreSQL": "postgresql.svg",
    "Postman": "postman.svg",
    "Postmates": "postmates.svg",
    "Power Apps": "powerapps.svg",
    "Power Automate": "powerautomate.svg",
    "Power BI": "powerbi.svg",
    "Power Fx": "powerfx.svg",
    "Power Pages": "powerpages.svg",
    "Power Virtual Agents": "powervirtualagents.svg",
    "POWERS": "powers.svg",
    "PowerShell": "powershell.svg",
    "pr.co": "prdotco.svg",
    "pre-commit": "precommit.svg",
    "Preact": "preact.svg",
    "Premier League": "premierleague.svg",
    "PrestaShop": "prestashop.svg",
    "Presto": "presto.svg",
    "Prettier": "prettier.svg",
    "Prevention": "prevention.svg",
    "Prezi": "prezi.svg",
    "Prime": "prime.svg",
    "Prime Video": "primevideo.svg",
    "Prisma": "prisma.svg",
    "Prismic": "prismic.svg",
    "Private Internet Access": "privateinternetaccess.svg",
    "Pro Tools": "protools.svg",
    "Probot": "probot.svg",
    "Processing Foundation": "processingfoundation.svg",
    "ProcessWire": "processwire.svg",
    "Product Hunt": "producthunt.svg",
    "Progate": "progate.svg",
    "Progress": "progress.svg",
    "Prometheus": "prometheus.svg",
    "ProSieben": "prosieben.svg",
    "Proto.io": "protodotio.svg",
    "protocols.io": "protocolsdotio.svg",
    "ProtonDB": "protondb.svg",
    "ProtonMail": "protonmail.svg",
    "ProtonVPN": "protonvpn.svg",
    "Protractor": "protractor.svg",
    "Proxmox": "proxmox.svg",
    "PUBG": "pubg.svg",
    "Publons": "publons.svg",
    "PubMed": "pubmed.svg",
    "Pug": "pug.svg",
    "Pulumi": "pulumi.svg",
    "Puma": "puma.svg",
    "Puppet": "puppet.svg",
    "Puppeteer": "puppeteer.svg",
    "PureScript": "purescript.svg",
    "PurgeCSS": "purgecss.svg",
    "Purism": "purism.svg",
    "Pusher": "pusher.svg",
    "PWA": "pwa.svg",
    "PyCharm": "pycharm.svg",
    "PyG": "pyg.svg",
    "PyPI": "pypi.svg",
    "PyPy": "pypy.svg",
    "PyScaffold": "pyscaffold.svg",
    "PySyft": "pysyft.svg",
    "Pytest": "pytest.svg",
    "Python": "python.svg",
    "PyTorch": "pytorch.svg",
    "PyTorch Lightning": "pytorchlightning.svg",
    "PyUp": "pyup.svg",
    "Qantas": "qantas.svg",
    "Qatar Airways": "qatarairways.svg",
    "QEMU": "qemu.svg",
    "Qgis": "qgis.svg",
    "Qi": "qi.svg",
    "Qiita": "qiita.svg",
    "Qiskit": "qiskit.svg",
    "QIWI": "qiwi.svg",
    "QMK": "qmk.svg",
    "Qt": "qt.svg",
    "Qualcomm": "qualcomm.svg",
    "Qualtrics": "qualtrics.svg",
    "Qualys": "qualys.svg",
    "Quantcast": "quantcast.svg",
    "QuantConnect": "quantconnect.svg",
    "Quarkus": "quarkus.svg",
    "Quasar": "quasar.svg",
    "Qubes OS": "qubesos.svg",
    "Quest": "quest.svg",
    "QuickBooks": "quickbooks.svg",
    "QuickLook": "quicklook.svg",
    "QuickTime": "quicktime.svg",
    "Quip": "quip.svg",
    "Quora": "quora.svg",
    "Qwiklabs": "qwiklabs.svg",
    "Qzone": "qzone.svg",
    "R": "r.svg",
    "R3": "r3.svg",
    "RabbitMQ": "rabbitmq.svg",
    "Racket": "racket.svg",
    "Radar": "radar.svg",
    "RadioPublic": "radiopublic.svg",
    "Railway": "railway.svg",
    "Rainmeter": "rainmeter.svg",
    "Rakuten": "rakuten.svg",
    "Ram": "ram.svg",
    "Rancher": "rancher.svg",
    "Rarible": "rarible.svg",
    "Rasa": "rasa.svg",
    "Raspberry Pi": "raspberrypi.svg",
    "Ravelry": "ravelry.svg",
    "Ray": "ray.svg",
    "Razer": "razer.svg",
    "Razorpay": "razorpay.svg",
    "React": "react.svg",
    "React Hook Form": "reacthookform.svg",
    "React Query": "reactquery.svg",
    "React Router": "reactrouter.svg",
    "React Table": "reacttable.svg",
    "ReactiveX": "reactivex.svg",
    "ReactOS": "reactos.svg",
    "Read the Docs": "readthedocs.svg",
    "ReadMe": "readme.svg",
    "Realm": "realm.svg",
    "Reason": "reason.svg",
    "Reason Studios": "reasonstudios.svg",
    "Red": "red.svg",
    "Red Hat": "redhat.svg",
    "Red Hat Open Shift": "redhatopenshift.svg",
    "Redbubble": "redbubble.svg",
    "Reddit": "reddit.svg",
    "Redis": "redis.svg",
    "Redmine": "redmine.svg",
    "Redux": "redux.svg",
    "Redux-Saga": "reduxsaga.svg",
    "RedwoodJS": "redwoodjs.svg",
    "Reebok": "reebok.svg",
    "Relay": "relay.svg",
    "Reliance Industries Limited": "relianceindustrieslimited.svg",
    "Remix": "remix.svg",
    "Ren'Py": "renpy.svg",
    "Renault": "renault.svg",
    "Render": "render.svg",
    "RenovateBot": "renovatebot.svg",
    "Renren": "renren.svg",
    "Replit": "replit.svg",
    "Republic of Gamers": "republicofgamers.svg",
    "ReScript": "rescript.svg",
    "RescueTime": "rescuetime.svg",
    "ResearchGate": "researchgate.svg",
    "ReSharper": "resharper.svg",
    "Resurrection Remix OS": "resurrectionremixos.svg",
    "RetroArch": "retroarch.svg",
    "RetroPie": "retropie.svg",
    "reveal.js": "revealdotjs.svg",
    "ReverbNation": "reverbnation.svg",
    "Revolt.chat": "revoltdotchat.svg",
    "Revolut": "revolut.svg",
    "Revue": "revue.svg",
    "REWE": "rewe.svg",
    "Rezgo": "rezgo.svg",
    "Rhinoceros": "rhinoceros.svg",
    "Rider": "rider.svg",
    "Rimac Automobili": "rimacautomobili.svg",
    "Ring": "ring.svg",
    "Riot Games": "riotgames.svg",
    "Ripple": "ripple.svg",
    "Riseup": "riseup.svg",
    "Roam Research": "roamresearch.svg",
    "Roblox": "roblox.svg",
    "Robot Framework": "robotframework.svg",
    "Rocket.Chat": "rocketdotchat.svg",
    "RocksDB": "rocksdb.svg",
    "Rocky Linux": "rockylinux.svg",
    "Roku": "roku.svg",
    "Rolls-Royce": "rollsroyce.svg",
    "rollup.js": "rollupdotjs.svg",
    "Rome": "rome.svg",
    "Roots": "roots.svg",
    "Roots Bedrock": "rootsbedrock.svg",
    "Roots Sage": "rootssage.svg",
    "ROS": "ros.svg",
    "Rossmann": "rossmann.svg",
    "Rotary International": "rotaryinternational.svg",
    "Rotten Tomatoes": "rottentomatoes.svg",
    "Roundcube": "roundcube.svg",
    "RSocket": "rsocket.svg",
    "RSS": "rss.svg",
    "RStudio": "rstudio.svg",
    "RTÉ": "rte.svg",
    "RTL": "rtl.svg",
    "RTLZWEI": "rtlzwei.svg",
    "RuboCop": "rubocop.svg",
    "Ruby": "ruby.svg",
    "Ruby on Rails": "rubyonrails.svg",
    "Ruby Sinatra": "rubysinatra.svg",
    "RubyGems": "rubygems.svg",
    "Runkeeper": "runkeeper.svg",
    "RunKit": "runkit.svg",
    "Rust": "rust.svg",
    "RxDB": "rxdb.svg",
    "Ryanair": "ryanair.svg",
    "S7 Airlines": "s7airlines.svg",
    "Sabanci": "sabanci.svg",
    "Safari": "safari.svg",
    "Sahibinden": "sahibinden.svg",
    "Sailfish OS": "sailfishos.svg",
    "Salesforce": "salesforce.svg",
    "Salt Project": "saltproject.svg",
    "Samsung": "samsung.svg",
    "Samsung Pay": "samsungpay.svg",
    "San Francisco Municipal Railway": "sanfranciscomunicipalrailway.svg",
    "SanDisk": "sandisk.svg",
    "São Paulo Metro": "saopaulometro.svg",
    "SAP": "sap.svg",
    "Sass": "sass.svg",
    "Sat.1": "sat1.svg",
    "Saturn": "saturn.svg",
    "Sauce Labs": "saucelabs.svg",
    "Scala": "scala.svg",
    "Scaleway": "scaleway.svg",
    "Scania": "scania.svg",
    "Schneider Electric": "schneiderelectric.svg",
    "scikit-learn": "scikitlearn.svg",
    "SciPy": "scipy.svg",
    "Scopus": "scopus.svg",
    "SCP Foundation": "scpfoundation.svg",
    "Scratch": "scratch.svg",
    "Screencastify": "screencastify.svg",
    "Scribd": "scribd.svg",
    "Scrimba": "scrimba.svg",
    "ScrollReveal": "scrollreveal.svg",
    "Scrum Alliance": "scrumalliance.svg",
    "Scrutinizer CI": "scrutinizerci.svg",
    "Seagate": "seagate.svg",
    "SEAT": "seat.svg",
    "SecurityScorecard": "securityscorecard.svg",
    "Sefaria": "sefaria.svg",
    "Sega": "sega.svg",
    "Selenium": "selenium.svg",
    "Sellfy": "sellfy.svg",
    "Semantic Scholar": "semanticscholar.svg",
    "Semantic UI React": "semanticuireact.svg",
    "Semantic Web": "semanticweb.svg",
    "semantic-release": "semanticrelease.svg",
    "Semaphore CI": "semaphoreci.svg",
    "SemVer": "semver.svg",
    "Sencha": "sencha.svg",
    "Sennheiser": "sennheiser.svg",
    "Sensu": "sensu.svg",
    "Sentry": "sentry.svg",
    "SEPA": "sepa.svg",
    "Sequelize": "sequelize.svg",
    "Server Fault": "serverfault.svg",
    "Serverless": "serverless.svg",
    "Sessionize": "sessionize.svg",
    "Setapp": "setapp.svg",
    "SFML": "sfml.svg",
    "Shadow": "shadow.svg",
    "Shanghai Metro": "shanghaimetro.svg",
    "sharp": "sharp.svg",
    "Shazam": "shazam.svg",
    "Shell": "shell.svg",
    "Shelly": "shelly.svg",
    "Shenzhen Metro": "shenzhenmetro.svg",
    "Shields.io": "shieldsdotio.svg",
    "Shikimori": "shikimori.svg",
    "Shopee": "shopee.svg",
    "Shopify": "shopify.svg",
    "Shopware": "shopware.svg",
    "Shotcut": "shotcut.svg",
    "Showpad": "showpad.svg",
    "Showtime": "showtime.svg",
    "Shutterstock": "shutterstock.svg",
    "Siemens": "siemens.svg",
    "Signal": "signal.svg",
    "Similarweb": "similarweb.svg",
    "Simkl": "simkl.svg",
    "Simple Analytics": "simpleanalytics.svg",
    "Simple Icons": "simpleicons.svg",
    "Simplenote": "simplenote.svg",
    "Sina Weibo": "sinaweibo.svg",
    "SingleStore": "singlestore.svg",
    "SitePoint": "sitepoint.svg",
    "Sketch": "sketch.svg",
    "Sketchfab": "sketchfab.svg",
    "SketchUp": "sketchup.svg",
    "Skillshare": "skillshare.svg",
    "ŠKODA": "skoda.svg",
    "Sky": "sky.svg",
    "Skynet": "skynet.svg",
    "Skypack": "skypack.svg",
    "Skype": "skype.svg",
    "Skype for Business": "skypeforbusiness.svg",
    "Slack": "slack.svg",
    "Slackware": "slackware.svg",
    "Slashdot": "slashdot.svg",
    "SlickPic": "slickpic.svg",
    "Slides": "slides.svg",
    "SlideShare": "slideshare.svg",
    "smart": "smart.svg",
    "SmartThings": "smartthings.svg",
    "smash.gg": "smashdotgg.svg",
    "Smashing Magazine": "smashingmagazine.svg",
    "SMRT": "smrt.svg",
    "SmugMug": "smugmug.svg",
    "Snapchat": "snapchat.svg",
    "Snapcraft": "snapcraft.svg",
    "Snowflake": "snowflake.svg",
    "Snowpack": "snowpack.svg",
    "Snyk": "snyk.svg",
    "Social Blade": "socialblade.svg",
    "Society6": "society6.svg",
    "Socket.io": "socketdotio.svg",
    "Sogou": "sogou.svg",
    "Solid": "solid.svg",
    "Solidity": "solidity.svg",
    "Sololearn": "sololearn.svg",
    "Solus": "solus.svg",
    "Sonar": "sonar.svg",
    "SonarCloud": "sonarcloud.svg",
    "SonarLint": "sonarlint.svg",
    "SonarQube": "sonarqube.svg",
    "SonarSource": "sonarsource.svg",
    "Songkick": "songkick.svg",
    "Songoda": "songoda.svg",
    "SonicWall": "sonicwall.svg",
    "Sonos": "sonos.svg",
    "Sony": "sony.svg",
    "Soundcharts": "soundcharts.svg",
    "SoundCloud": "soundcloud.svg",
    "Source Engine": "sourceengine.svg",
    "SourceForge": "sourceforge.svg",
    "Sourcegraph": "sourcegraph.svg",
    "Sourcetree": "sourcetree.svg",
    "Southwest Airlines": "southwestairlines.svg",
    "Spacemacs": "spacemacs.svg",
    "SpaceX": "spacex.svg",
    "spaCy": "spacy.svg",
    "Spark AR": "sparkar.svg",
    "Sparkasse": "sparkasse.svg",
    "SparkFun": "sparkfun.svg",
    "SparkPost": "sparkpost.svg",
    "SPDX": "spdx.svg",
    "Speaker Deck": "speakerdeck.svg",
    "Spectrum": "spectrum.svg",
    "Speedtest": "speedtest.svg",
    "Spinnaker": "spinnaker.svg",
    "Spinrilla": "spinrilla.svg",
    "Splunk": "splunk.svg",
    "Spond": "spond.svg",
    "Spotify": "spotify.svg",
    "Spotlight": "spotlight.svg",
    "Spreadshirt": "spreadshirt.svg",
    "Spreaker": "spreaker.svg",
    "Spring": "spring.svg",
    "Spring": "spring_creators.svg",
    "Spring Boot": "springboot.svg",
    "Spring Security": "springsecurity.svg",
    "Spyder IDE": "spyderide.svg",
    "SQLite": "sqlite.svg",
    "Square": "square.svg",
    "Square Enix": "squareenix.svg",
    "Squarespace": "squarespace.svg",
    "SSRN": "ssrn.svg",
    "Stack Exchange": "stackexchange.svg",
    "Stack Overflow": "stackoverflow.svg",
    "Stackbit": "stackbit.svg",
    "StackBlitz": "stackblitz.svg",
    "StackEdit": "stackedit.svg",
    "StackPath": "stackpath.svg",
    "StackShare": "stackshare.svg",
    "Stadia": "stadia.svg",
    "Staffbase": "staffbase.svg",
    "StandardJS": "standardjs.svg",
    "Star Trek": "startrek.svg",
    "Starbucks": "starbucks.svg",
    "Stardock": "stardock.svg",
    "Starling Bank": "starlingbank.svg",
    "Starship": "starship.svg",
    "STARZ": "starz.svg",
    "Statamic": "statamic.svg",
    "Statuspage": "statuspage.svg",
    "Statuspal": "statuspal.svg",
    "Steam": "steam.svg",
    "Steam Deck": "steamdeck.svg",
    "SteamDB": "steamdb.svg",
    "Steamworks": "steamworks.svg",
    "Steelseries": "steelseries.svg",
    "Steem": "steem.svg",
    "Steemit": "steemit.svg",
    "Steinberg": "steinberg.svg",
    "Stellar": "stellar.svg",
    "Stencyl": "stencyl.svg",
    "Stimulus": "stimulus.svg",
    "Stitcher": "stitcher.svg",
    "STMicroelectronics": "stmicroelectronics.svg",
    "StopStalk": "stopstalk.svg",
    "Storyblok": "storyblok.svg",
    "Storybook": "storybook.svg",
    "Strapi": "strapi.svg",
    "Strava": "strava.svg",
    "Streamlit": "streamlit.svg",
    "Stripe": "stripe.svg",
    "strongSwan": "strongswan.svg",
    "StubHub": "stubhub.svg",
    "styled-components": "styledcomponents.svg",
    "stylelint": "stylelint.svg",
    "StyleShare": "styleshare.svg",
    "Stylus": "stylus.svg",
    "Subaru": "subaru.svg",
    "Sublime Text": "sublimetext.svg",
    "Substack": "substack.svg",
    "Subversion": "subversion.svg",
    "suckless": "suckless.svg",
    "Sumo Logic": "sumologic.svg",
    "Supabase": "supabase.svg",
    "Super User": "superuser.svg",
    "Supermicro": "supermicro.svg",
    "SurrealDB": "surrealdb.svg",
    "SurveyMonkey": "surveymonkey.svg",
    "SUSE": "suse.svg",
    "Suzuki": "suzuki.svg",
    "Svelte": "svelte.svg",
    "SVG": "svg.svg",
    "SVGO": "svgo.svg",
    "Swagger": "swagger.svg",
    "Swarm": "swarm.svg",
    "SWC": "swc.svg",
    "Swift": "swift.svg",
    "Swiggy": "swiggy.svg",
    "Swiper": "swiper.svg",
    "Symantec": "symantec.svg",
    "Symfony": "symfony.svg",
    "Symphony": "symphony.svg",
    "SymPy": "sympy.svg",
    "Synology": "synology.svg",
    "System76": "system76.svg",
    "T-Mobile": "tmobile.svg",
    "Tableau": "tableau.svg",
    "TableCheck": "tablecheck.svg",
    "Taco Bell": "tacobell.svg",
    "tado°": "tado.svg",
    "Taichi Graphics": "taichigraphics.svg",
    "Taichi Lang": "taichilang.svg",
    "Tails": "tails.svg",
    "Tailwind CSS": "tailwindcss.svg",
    "Talend": "talend.svg",
    "Talenthouse": "talenthouse.svg",
    "Tamiya": "tamiya.svg",
    "Tampermonkey": "tampermonkey.svg",
    "Taobao": "taobao.svg",
    "Tapas": "tapas.svg",
    "Target": "target.svg",
    "Task": "task.svg",
    "Tasmota": "tasmota.svg",
    "Tata": "tata.svg",
    "Tauri": "tauri.svg",
    "TaxBuzz": "taxbuzz.svg",
    "TeamCity": "teamcity.svg",
    "TeamSpeak": "teamspeak.svg",
    "TeamViewer": "teamviewer.svg",
    "TED": "ted.svg",
    "Teespring": "teespring.svg",
    "Tekton": "tekton.svg",
    "TELE5": "tele5.svg",
    "Telegram": "telegram.svg",
    "Telegraph": "telegraph.svg",
    "Temporal": "temporal.svg",
    "Tencent QQ": "tencentqq.svg",
    "TensorFlow": "tensorflow.svg",
    "Teradata": "teradata.svg",
    "teratail": "teratail.svg",
    "Terraform": "terraform.svg",
    "Tesco": "tesco.svg",
    "Tesla": "tesla.svg",
    "TestCafe": "testcafe.svg",
    "Testin": "testin.svg",
    "Testing Library": "testinglibrary.svg",
    "Tether": "tether.svg",
    "Textpattern": "textpattern.svg",
    "The Algorithms": "thealgorithms.svg",
    "The Conversation": "theconversation.svg",
    "The Irish Times": "theirishtimes.svg",
    "The Mighty": "themighty.svg",
    "The Models Resource": "themodelsresource.svg",
    "The Movie Database": "themoviedatabase.svg",
    "The North Face": "thenorthface.svg",
    "The Register": "theregister.svg",
    "The Sounds Resource": "thesoundsresource.svg",
    "The Spriters Resource": "thespritersresource.svg",
    "The Washington Post": "thewashingtonpost.svg",
    "Thingiverse": "thingiverse.svg",
    "ThinkPad": "thinkpad.svg",
    "Threadless": "threadless.svg",
    "Three.js": "threedotjs.svg",
    "Threema": "threema.svg",
    "Thumbtack": "thumbtack.svg",
    "Thunderbird": "thunderbird.svg",
    "Thymeleaf": "thymeleaf.svg",
    "Ticketmaster": "ticketmaster.svg",
    "Tidal": "tidal.svg",
    "Tide": "tide.svg",
    "Tidyverse": "tidyverse.svg",
    "TietoEVRY": "tietoevry.svg",
    "TikTok": "tiktok.svg",
    "Tile": "tile.svg",
    "Timescale": "timescale.svg",
    "Tinder": "tinder.svg",
    "TinyLetter": "tinyletter.svg",
    "Tistory": "tistory.svg",
    "tmux": "tmux.svg",
    "Todoist": "todoist.svg",
    "Toggl": "toggl.svg",
    "Tokyo Metro": "tokyometro.svg",
    "Tomorrowland": "tomorrowland.svg",
    "Topcoder": "topcoder.svg",
    "Toptal": "toptal.svg",
    "Tor Browser": "torbrowser.svg",
    "Tor Project": "torproject.svg",
    "Toshiba": "toshiba.svg",
    "Toyota": "toyota.svg",
    "TP-Link": "tplink.svg",
    "tqdm": "tqdm.svg",
    "Traefik Mesh": "traefikmesh.svg",
    "Traefik Proxy": "traefikproxy.svg",
    "TrainerRoad": "trainerroad.svg",
    "Trakt": "trakt.svg",
    "Transport for Ireland": "transportforireland.svg",
    "Transport for London": "transportforlondon.svg",
    "Travis CI": "travisci.svg",
    "Treehouse": "treehouse.svg",
    "Trello": "trello.svg",
    "Trend Micro": "trendmicro.svg",
    "Treyarch": "treyarch.svg",
    "Triller": "triller.svg",
    "Trino": "trino.svg",
    "Trip.com": "tripdotcom.svg",
    "Tripadvisor": "tripadvisor.svg",
    "Trove": "trove.svg",
    "tRPC": "trpc.svg",
    "TrueNAS": "truenas.svg",
    "trulia": "trulia.svg",
    "Trusted Shops": "trustedshops.svg",
    "Trustpilot": "trustpilot.svg",
    "Try It Online": "tryitonline.svg",
    "TryHackMe": "tryhackme.svg",
    "ts-node": "tsnode.svg",
    "Tubi": "tubi.svg",
    "TUI": "tui.svg",
    "Tumblr": "tumblr.svg",
    "TuneIn": "tunein.svg",
    "Turborepo": "turborepo.svg",
    "TurboSquid": "turbosquid.svg",
    "Turkish Airlines": "turkishairlines.svg",
    "Tutanota": "tutanota.svg",
    "TV Time": "tvtime.svg",
    "Twilio": "twilio.svg",
    "Twitch": "twitch.svg",
    "Twitter": "twitter.svg",
    "Twoo": "twoo.svg",
    "Typeform": "typeform.svg",
    "TypeScript": "typescript.svg",
    "TYPO3": "typo3.svg",
    "Uber": "uber.svg",
    "Uber Eats": "ubereats.svg",
    "Ubiquiti": "ubiquiti.svg",
    "Ubisoft": "ubisoft.svg",
    "uBlock Origin": "ublockorigin.svg",
    "Ubuntu": "ubuntu.svg",
    "Udacity": "udacity.svg",
    "Udemy": "udemy.svg",
    "UFC": "ufc.svg",
    "UIkit": "uikit.svg",
    "Ulule": "ulule.svg",
    "Umbraco": "umbraco.svg",
    "Unacademy": "unacademy.svg",
    "Under Armour": "underarmour.svg",
    "Underscore.js": "underscoredotjs.svg",
    "Undertale": "undertale.svg",
    "Unicode": "unicode.svg",
    "Unilever": "unilever.svg",
    "United Airlines": "unitedairlines.svg",
    "Unity": "unity.svg",
    "Unlicense": "unlicense.svg",
    "UnoCSS": "unocss.svg",
    "Unraid": "unraid.svg",
    "Unreal Engine": "unrealengine.svg",
    "Unsplash": "unsplash.svg",
    "Untangle": "untangle.svg",
    "Untappd": "untappd.svg",
    "UpCloud": "upcloud.svg",
    "UpLabs": "uplabs.svg",
    "Uploaded": "uploaded.svg",
    "UPS": "ups.svg",
    "Upstash": "upstash.svg",
    "Uptime Kuma": "uptimekuma.svg",
    "Uptobox": "uptobox.svg",
    "Upwork": "upwork.svg",
    "USPS": "usps.svg",
    "V": "v.svg",
    "V2EX": "v2ex.svg",
    "V8": "v8.svg",
    "Vaadin": "vaadin.svg",
    "Vagrant": "vagrant.svg",
    "Valorant": "valorant.svg",
    "Valve": "valve.svg",
    "Vapor": "vapor.svg",
    "Vault": "vault.svg",
    "Vauxhall": "vauxhall.svg",
    "vBulletin": "vbulletin.svg",
    "Vector Logo Zone": "vectorlogozone.svg",
    "Vectorworks": "vectorworks.svg",
    "Veeam": "veeam.svg",
    "Veepee": "veepee.svg",
    "Velog": "velog.svg",
    "Venmo": "venmo.svg",
    "Vercel": "vercel.svg",
    "Verdaccio": "verdaccio.svg",
    "Veritas": "veritas.svg",
    "Verizon": "verizon.svg",
    "VEXXHOST": "vexxhost.svg",
    "vFairs": "vfairs.svg",
    "Viadeo": "viadeo.svg",
    "Viber": "viber.svg",
    "Vim": "vim.svg",
    "Vimeo": "vimeo.svg",
    "Vimeo Livestream": "vimeolivestream.svg",
    "Virgin": "virgin.svg",
    "Virgin Media": "virginmedia.svg",
    "VirtualBox": "virtualbox.svg",
    "VirusTotal": "virustotal.svg",
    "Visa": "visa.svg",
    "Visual Studio": "visualstudio.svg",
    "Visual Studio Code": "visualstudiocode.svg",
    "Vite": "vite.svg",
    "Vitess": "vitess.svg",
    "Vitest": "vitest.svg",
    "Vivaldi": "vivaldi.svg",
    "Vivino": "vivino.svg",
    "VK": "vk.svg",
    "VLC media player": "vlcmediaplayer.svg",
    "VMware": "vmware.svg",
    "Vodafone": "vodafone.svg",
    "Volkswagen": "volkswagen.svg",
    "Volvo": "volvo.svg",
    "Vonage": "vonage.svg",
    "Vowpal Wabbit": "vowpalwabbit.svg",
    "VOX": "vox.svg",
    "VSCO": "vsco.svg",
    "VSCodium": "vscodium.svg",
    "VTEX": "vtex.svg",
    "Vue.js": "vuedotjs.svg",
    "Vuetify": "vuetify.svg",
    "Vulkan": "vulkan.svg",
    "Vultr": "vultr.svg",
    "W3C": "w3c.svg",
    "Wacom": "wacom.svg",
    "Wagtail": "wagtail.svg",
    "Wails": "wails.svg",
    "WakaTime": "wakatime.svg",
    "WALKMAN": "walkman.svg",
    "Wallabag": "wallabag.svg",
    "Walmart": "walmart.svg",
    "Wantedly": "wantedly.svg",
    "Wappalyzer": "wappalyzer.svg",
    "Warner Bros.": "warnerbros.svg",
    "Warp": "warp.svg",
    "wasmCloud": "wasmcloud.svg",
    "Wasmer": "wasmer.svg",
    "Wattpad": "wattpad.svg",
    "Waze": "waze.svg",
    "Wear OS": "wearos.svg",
    "Weasyl": "weasyl.svg",
    "Web3.js": "web3dotjs.svg",
    "WebAssembly": "webassembly.svg",
    "WebAuthn": "webauthn.svg",
    "webcomponents.org": "webcomponentsdotorg.svg",
    "WebdriverIO": "webdriverio.svg",
    "Webflow": "webflow.svg",
    "WebGL": "webgl.svg",
    "webhint": "webhint.svg",
    "Weblate": "weblate.svg",
    "Webmin": "webmin.svg",
    "WebMoney": "webmoney.svg",
    "Webpack": "webpack.svg",
    "WebRTC": "webrtc.svg",
    "WebStorm": "webstorm.svg",
    "WEBTOON": "webtoon.svg",
    "WeChat": "wechat.svg",
    "WeGame": "wegame.svg",
    "Weights & Biases": "weightsandbiases.svg",
    "Welcome to the Jungle": "welcometothejungle.svg",
    "WEMO": "wemo.svg",
    "Western Digital": "westerndigital.svg",
    "WeTransfer": "wetransfer.svg",
    "WhatsApp": "whatsapp.svg",
    "When I Work": "wheniwork.svg",
    "WhiteSource": "whitesource.svg",
    "Wii": "wii.svg",
    "Wii U": "wiiu.svg",
    "Wiki.js": "wikidotjs.svg",
    "Wikidata": "wikidata.svg",
    "Wikimedia Commons": "wikimediacommons.svg",
    "Wikipedia": "wikipedia.svg",
    "Wikiquote": "wikiquote.svg",
    "Wikivoyage": "wikivoyage.svg",
    "Winamp": "winamp.svg",
    "Windi CSS": "windicss.svg",
    "Windows": "windows.svg",
    "Windows 11": "windows11.svg",
    "Windows 95": "windows95.svg",
    "Windows Terminal": "windowsterminal.svg",
    "Windows XP": "windowsxp.svg",
    "Winmate": "winmate.svg",
    "Wipro": "wipro.svg",
    "Wire": "wire.svg",
    "WireGuard": "wireguard.svg",
    "Wireshark": "wireshark.svg",
    "Wise": "wise.svg",
    "Wish": "wish.svg",
    "Wistia": "wistia.svg",
    "Wix": "wix.svg",
    "Wizz Air": "wizzair.svg",
    "Wolfram": "wolfram.svg",
    "Wolfram Language": "wolframlanguage.svg",
    "Wolfram Mathematica": "wolframmathematica.svg",
    "Woo": "woo.svg",
    "WooCommerce": "woocommerce.svg",
    "WordPress": "wordpress.svg",
    "Workplace": "workplace.svg",
    "World Health Organization": "worldhealthorganization.svg",
    "WP Engine": "wpengine.svg",
    "WP Rocket": "wprocket.svg",
    "WPExplorer": "wpexplorer.svg",
    "write.as": "writedotas.svg",
    "WWE": "wwe.svg",
    "Wwise": "wwise.svg",
    "X.Org": "xdotorg.svg",
    "Xamarin": "xamarin.svg",
    "XAML": "xaml.svg",
    "XAMPP": "xampp.svg",
    "Xbox": "xbox.svg",
    "Xcode": "xcode.svg",
    "XDA Developers": "xdadevelopers.svg",
    "Xero": "xero.svg",
    "XFCE": "xfce.svg",
    "Xiaomi": "xiaomi.svg",
    "Xilinx": "xilinx.svg",
    "Xing": "xing.svg",
    "XMPP": "xmpp.svg",
    "XO": "xo.svg",
    "XRP": "xrp.svg",
    "XSplit": "xsplit.svg",
    "XState": "xstate.svg",
    "Y Combinator": "ycombinator.svg",
    "Yahoo!": "yahoo.svg",
    "Yale": "yale.svg",
    "Yamaha Corporation": "yamahacorporation.svg",
    "Yamaha Motor Corporation": "yamahamotorcorporation.svg",
    "Yammer": "yammer.svg",
    "Yarn": "yarn.svg",
    "Yelp": "yelp.svg",
    "Yoast": "yoast.svg",
    "YOLO": "yolo.svg",
    "YourTravel.TV": "yourtraveldottv.svg",
    "YouTube": "youtube.svg",
    "YouTube Gaming": "youtubegaming.svg",
    "YouTube Music": "youtubemusic.svg",
    "YouTube Studio": "youtubestudio.svg",
    "YouTube TV": "youtubetv.svg",
    "Yubico": "yubico.svg",
    "Z-Wave": "zwave.svg",
    "Żabka": "zabka.svg",
    "Zalando": "zalando.svg",
    "Zalo": "zalo.svg",
    "Zapier": "zapier.svg",
    "Zara": "zara.svg",
    "Zazzle": "zazzle.svg",
    "Zcash": "zcash.svg",
    "ZDF": "zdf.svg",
    "Zebra Technologies": "zebratechnologies.svg",
    "Zelle": "zelle.svg",
    "Zend": "zend.svg",
    "Zend Framework": "zendframework.svg",
    "Zendesk": "zendesk.svg",
    "Zenn": "zenn.svg",
    "Zenodo": "zenodo.svg",
    "Zerodha": "zerodha.svg",
    "ZeroMQ": "zeromq.svg",
    "Zerply": "zerply.svg",
    "Zettlr": "zettlr.svg",
    "Zhihu": "zhihu.svg",
    "Zig": "zig.svg",
    "Zigbee": "zigbee.svg",
    "Zillow": "zillow.svg",
    "ZincSearch": "zincsearch.svg",
    "Zingat": "zingat.svg",
    "Zoho": "zoho.svg",
    "Zoiper": "zoiper.svg",
    "Zomato": "zomato.svg",
    "Zoom": "zoom.svg",
    "Zorin": "zorin.svg",
    "Zotero": "zotero.svg",
    "Zulip": "zulip.svg",
    "Zyte": "zyte.svg",
}


def svg_encode(svg):
    # Ref: https://bl.ocks.org/jennyknuth/222825e315d45a738ed9d6e04c7a88d0
    # Encode an SVG string so it can be embedded into a data URL.
    enc_chars = '"%#{}<>'  # Encode these to %hex
    enc_chars_maybe = "&|[]^`;?:@="  # Add to enc_chars on exception
    svg_enc = ""
    # Translate character by character
    for c in str(svg):
        if c in enc_chars:
            if c == '"':
                svg_enc += "'"
            else:
                svg_enc += "%" + format(ord(c), "x")
        else:
            svg_enc += c
    return " ".join(svg_enc.split())  # Compact whitespace


source_file = "./links.css"

string = ""

for file in os.listdir("icons"):
    name = file.split(".")[0]
    # find as value
    try:
        brand = [k for k, v in names.items() if v == name][0]
    except IndexError:
        brand = name
    print(f"/* {brand} */")
    string += f"/* {brand} */\n"
    with open(f"icons/{file}", "r") as f:
        svg = f.read()
        # encode as url
        svg = svg_encode(svg)
        # replace url("brandname.svg") with url("data:image/svg+xml url-encoded")
        with open(source_file, "r") as f:
            links = f.read()
            links = links.replace(
                f"url('{name}.svg')", f'url("data:image/svg+xml,{svg}")'
            )
        with open(source_file, "w") as f:
            f.write(links)


